const QUIZ_DATA = {
    states: [
      { name: "Andhra Pradesh", capital: "Amaravati", phonetic: "Andhra Pradesh" },
      { name: "Arunachal Pradesh", capital: "Itanagar", phonetic: "Arunachal Pradesh" },
      { name: "Assam", capital: "Dispur", phonetic: "Assam" },
      { name: "Bihar", capital: "Patna", phonetic: "Bihar" },
      { name: "Chhattisgarh", capital: "Raipur", phonetic: "Chhattisgarh" },
      { name: "Goa", capital: "Panaji", phonetic: "Goa" },
      { name: "Gujarat", capital: "Gandhinagar", phonetic: "Gujarat" },
      { name: "Haryana", capital: "Chandigarh", phonetic: "Haryana" },
      { name: "Himachal Pradesh", capital: "Shimla", phonetic: "Himachal Pradesh" },
      { name: "Jharkhand", capital: "Ranchi", phonetic: "Jharkhand" },
      { name: "Karnataka", capital: "Bengaluru", phonetic: "Karnataka" },
      { name: "Kerala", capital: "Thiruvananthapuram", phonetic: "Kerala" },
      { name: "Madhya Pradesh", capital: "Bhopal", phonetic: "Madhya Pradesh" },
      { name: "Maharashtra", capital: "Mumbai", phonetic: "Maharashtra" },
      { name: "Manipur", capital: "Imphal", phonetic: "Manipur" },
      { name: "Meghalaya", capital: "Shillong", phonetic: "Meghalaya" },
      { name: "Mizoram", capital: "Aizawl", phonetic: "Mizoram" },
      { name: "Nagaland", capital: "Kohima", phonetic: "Nagaland" },
      { name: "Odisha", capital: "Bhubaneswar", phonetic: "Odisha" },
      { name: "Punjab", capital: "Chandigarh", phonetic: "Punjab" },
      { name: "Rajasthan", capital: "Jaipur", phonetic: "Rajasthan" },
      { name: "Sikkim", capital: "Gangtok", phonetic: "Sikkim" },
      { name: "Tamil Nadu", capital: "Chennai", phonetic: "Tamil Nadu" },
      { name: "Telangana", capital: "Hyderabad", phonetic: "Telangana" },
      { name: "Tripura", capital: "Agartala", phonetic: "Tripura" },
      { name: "Uttarakhand", capital: "Dehradun", phonetic: "Uttarakhand" },
      { name: "Uttar Pradesh", capital: "Lucknow", phonetic: "Uttar Pradesh" },
      { name: "West Bengal", capital: "Kolkata", phonetic: "West Bengal" }
    ],

    uts: [
      { name: "Andaman and Nicobar Islands", capital: "Port Blair", phonetic: "Andaman and Nicobar Islands" },
      { name: "Chandigarh", capital: "Chandigarh", phonetic: "Chandigarh" },
      { name: "Dadra and Nagar Haveli and Daman and Diu", capital: "Daman", phonetic: "Dadra and Nagar Haveli and Daman and Diu" },
      { name: "Delhi", capital: "New Delhi", phonetic: "Delhi" },
      { name: "Jammu and Kashmir", capital: "Srinagar", phonetic: "Jammu and Kashmir" },
      { name: "Ladakh", capital: "Leh", phonetic: "Ladakh" },
      { name: "Lakshadweep", capital: "Kavaratti", phonetic: "Lakshadweep" },
      { name: "Puducherry", capital: "Puducherry", phonetic: "Puducherry" }
    ],
    math: Array.from({ length: 20 }, (_, i) => {
        const a = Math.floor(Math.random() * 9) + 1;
        const b = Math.floor(Math.random() * 9) + 1;
        const fruits = ['🍎', '🍊', '🍌', '🍇', '🍓', '🥭'];
        const fruit = fruits[Math.floor(Math.random() * fruits.length)];
        return {
            num1: a,
            num2: b,
            capital: (a + b).toString(),
            name: `${a} + ${b}`,
            fruit: fruit
        };
    }),
    subtraction: Array.from({ length: 20 }, (_, i) => {
        const a = Math.floor(Math.random() * 9) + 1;
        const b = Math.floor(Math.random() * a) + 1;
        const fruits = ['🍎', '🍊', '🍌', '🍇', '🍓', '🥭'];
        const fruit = fruits[Math.floor(Math.random() * fruits.length)];
        return {
            num1: a,
            num2: b,
            capital: (a - b).toString(),
            name: `${a} - ${b}`,
            fruit: fruit
        };
    }),
    monuments: [
        { name: "Taj Mahal", capital: "Agra", phonetic: "Taj Mahal", image: "assets/monument-images/01_Taj_Mahal.jpg" },
        { name: "Hawa Mahal", capital: "Jaipur", phonetic: "Hawa Mahal", image: "assets/monument-images/02_Hawa_Mahal.jpg" },
        { name: "Gateway of India", capital: "Mumbai", phonetic: "Gateway of India", image: "assets/monument-images/03_Gateway_of_India.jpg" },
        { name: "Golden Temple", capital: "Amritsar", phonetic: "Golden Temple", image: "assets/monument-images/04_Golden_Temple.jpg" },
        { name: "Qutub Minar", capital: "Delhi", phonetic: "Qutub Minar", image: "assets/monument-images/05_Qutub_Minar.jpg" },
        { name: "Charminar", capital: "Hyderabad", phonetic: "Charminar", image: "assets/monument-images/06_Charminar.jpg" },
        { name: "Victoria Memorial", capital: "Kolkata", phonetic: "Victoria Memorial", image: "assets/monument-images/07_Victoria_Memorial.jpg" },
        { name: "Amer Fort", capital: "Jaipur", phonetic: "Amer Fort", image: "assets/monument-images/08_Amer_Fort.jpg" },
        { name: "Lotus Temple", capital: "Delhi", phonetic: "Lotus Temple", image: "assets/monument-images/09_Lotus_Temple.jpg" },
        { name: "Red Fort", capital: "Delhi", phonetic: "Red Fort", image: "assets/monument-images/10_Red_Fort.jpg" },
        { name: "India Gate", capital: "Delhi", phonetic: "India Gate", image: "assets/monument-images/11_India_Gate.jpg" },
        { name: "Mysore Palace", capital: "Mysuru", phonetic: "Mysore Palace", image: "assets/monument-images/12_Mysore_Palace.jpg" },
        { name: "Konark Sun Temple", capital: "Konark", phonetic: "Konark Sun Temple", image: "assets/monument-images/13_Konark_Sun_Temple.jpg" },
        { name: "Ajanta Caves", capital: "Chhatrapati Sambhajinagar", phonetic: "Ajanta Caves", image: "assets/monument-images/14_Ajanta_Caves.jpg" },
        { name: "Meenakshi Temple", capital: "Madurai", phonetic: "Meenakshi Temple", image: "assets/monument-images/15_Meenakshi_Temple.jpg" },
        { name: "Vivekananda Rock", capital: "Kanyakumari", phonetic: "Vivekananda Rock", image: "assets/monument-images/16_Vivekananda_Rock.jpg" },
        { name: "Gol Gumbaz", capital: "Bijapur", phonetic: "Gol Gumbaz", image: "assets/monument-images/17_Gol_Gumbaz.jpg" },
        { name: "Jantar Mantar", capital: "Jaipur", phonetic: "Jantar Mantar", image: "assets/monument-images/18_Jantar_Mantar.jpg" },
        { name: "Chhatrapati Shivaji Terminus", capital: "Mumbai", phonetic: "Chhatrapati Shivaji Terminus", image: "assets/monument-images/19_CST_Mumbai.jpg" },
        { name: "Sanchi Stupa", capital: "Sanchi", phonetic: "Sanchi Stupa", image: "assets/monument-images/20_Sanchi_Stupa.jpg" },

        { name: "Ellora Caves", capital: "Chhatrapati Sambhajinagar", phonetic: "Ellora Caves", image: "assets/monument-images/21_Ellora_Caves.png" },
        { name: "Brihadeeswara Temple", capital: "Thanjavur", phonetic: "Brihadeeswara Temple", image: "assets/monument-images/22_Brihadeeswara_Temple.png" },
        { name: "Khajuraho Temples", capital: "Khajuraho", phonetic: "Khajuraho Temples", image: "assets/monument-images/23_Khajuraho_Temples.png" },
        { name: "Rani ki Vav", capital: "Patan", phonetic: "Rani ki Vav", image: "assets/monument-images/24_Rani_ki_Vav.png" },
        { name: "Fatehpur Sikri", capital: "Fatehpur Sikri", phonetic: "Fatehpur Sikri", image: "assets/monument-images/25_Fatehpur_Sikri.png" },
        { name: "Humayun's Tomb", capital: "Delhi", phonetic: "Humayun's Tomb", image: "assets/monument-images/26_Humayuns_Tomb.png" },
        { name: "Akshardham Temple", capital: "Delhi", phonetic: "Akshardham Temple", image: "assets/monument-images/27_Akshardham_Temple.png" },
        { name: "Somnath Temple", capital: "Somnath", phonetic: "Somnath Temple", image: "assets/monument-images/28_Somnath_Temple.png" },
        { name: "Mahabodhi Temple", capital: "Bodh Gaya", phonetic: "Mahabodhi Temple", image: "assets/monument-images/29_Mahabodhi_Temple.png" },
        { name: "Hampi Ruins", capital: "Hampi", phonetic: "Hampi Ruins", image: "assets/monument-images/30_Hampi_Ruins.png" },
        { name: "Gwalior Fort", capital: "Gwalior", phonetic: "Gwalior Fort", image: "assets/monument-images/31_Gwalior_Fort.png" },
        { name: "Mehrangarh Fort", capital: "Jodhpur", phonetic: "Mehrangarh Fort", image: "assets/monument-images/32_Mehrangarh_Fort.png" },
        { name: "City Palace Udaipur", capital: "Udaipur", phonetic: "City Palace Udaipur", image: "assets/monument-images/33_City_Palace_Udaipur.png" },
        { name: "Lake Palace", capital: "Udaipur", phonetic: "Lake Palace", image: "assets/monument-images/34_Lake_Palace.png" },
        { name: "Nalanda University Ruins", capital: "Nalanda", phonetic: "Nalanda University Ruins", image: "assets/monument-images/35_Nalanda_Ruins.png" },
        { name: "Elephanta Caves", capital: "Mumbai", phonetic: "Elephanta Caves", image: "assets/monument-images/36_Elephanta_Caves.png" },
        { name: "Shaniwar Wada", capital: "Pune", phonetic: "Shaniwar Wada", image: "assets/monument-images/37_Shaniwar_Wada.png" },
        { name: "Agra Fort", capital: "Agra", phonetic: "Agra Fort", image: "assets/monument-images/38_Agra_Fort.png" },
        { name: "Safdarjung Tomb", capital: "Delhi", phonetic: "Safdarjung Tomb", image: "assets/monument-images/39_Safdarjung_Tomb.png" },
        { name: "Purana Qila", capital: "Delhi", phonetic: "Purana Qila", image: "assets/monument-images/40_Purana_Qila.png" },
        { name: "Lingaraj Temple", capital: "Bhubaneswar", phonetic: "Lingaraj Temple", image: "assets/monument-images/41_Lingaraj_Temple.png" },
        { name: "Jagannath Temple", capital: "Puri", phonetic: "Jagannath Temple", image: "assets/monument-images/42_Jagannath_Temple.png" },
        { name: "Padmanabhaswamy Temple", capital: "Thiruvananthapuram", phonetic: "Padmanabhaswamy Temple", image: "assets/monument-images/43_Padmanabhaswamy_Temple.png" },
        { name: "Bekal Fort", capital: "Kasaragod", phonetic: "Bekal Fort", image: "assets/monument-images/44_Bekal_Fort.png" },
        { name: "Chittorgarh Fort", capital: "Chittorgarh", phonetic: "Chittorgarh Fort", image: "assets/monument-images/45_Chittorgarh_Fort.png" },
        { name: "Ranthambore Fort", capital: "Sawai Madhopur", phonetic: "Ranthambore Fort", image: "assets/monument-images/46_Ranthambore_Fort.png" },
        { name: "Tawang Monastery", capital: "Tawang", phonetic: "Tawang Monastery", image: "assets/monument-images/47_Tawang_Monastery.png" },
        { name: "Rumtek Monastery", capital: "Gangtok", phonetic: "Rumtek Monastery", image: "assets/monument-images/48_Rumtek_Monastery.png" },
        { name: "Udayagiri Caves", capital: "Vidisha", phonetic: "Udayagiri Caves", image: "assets/monument-images/49_Udayagiri_Caves.png" },
        { name: "Barabar Caves", capital: "Jehanabad", phonetic: "Barabar Caves", image: "assets/monument-images/50_Barabar_Caves.png" }

    ],
    symbols: [
      { name: "National Animal", capital: "Tiger", category: "animal", emoji: "🐅" },
      { name: "National Bird", capital: "Peacock", category: "bird", emoji: "🦚" },
      { name: "National Fruit", capital: "Mango", category: "fruit", emoji: "🥭" },
      { name: "National Flower", capital: "Lotus", category: "flower", emoji: "🪷" },
      { name: "National Tree", capital: "Banyan Tree", category: "tree", emoji: "🌳" },
      { name: "National River", capital: "Ganga", category: "river", emoji: "🌊" },
      { name: "National Aquatic Animal", capital: "Dolphin", category: "aquatic animal", emoji: "🐬" },
      { name: "National Heritage Animal", capital: "Elephant", category: "heritage animal", emoji: "🐘" },
      { name: "National Game", capital: "Hockey", category: "game", emoji: "🏑" },
      { name: "National Motto", capital: "Satyameva Jayate", category: "motto", emoji: "🇮🇳" },
      { name: "National Reptile", capital: "King Cobra", category: "reptile", emoji: "🐍" },
      { name: "National Microbe", capital: "Lactobacillus", category: "microbe", emoji: "🥛" },
      { name: "National Vegetable", capital: "Pumpkin", category: "vegetable", emoji: "🎃" },
      { name: "National Song", capital: "Vande Mataram", category: "song", emoji: "🎶" },
      { name: "National Anthem", capital: "Jana Gana Mana", category: "anthem", emoji: "🎵" }
    ],
     families: [
       { name: "Lion", capital: "Cub", emoji: "🦁", image: "assets/animal-images/01_Lion_Cub.jpg" },
       { name: "Dog", capital: "Puppy", emoji: "🐶", image: "assets/animal-images/02_Dog_Puppy.jpg" },
       { name: "Cat", capital: "Kitten", emoji: "🐱", image: "assets/animal-images/03_Cat_Kitten.jpg" },
       { name: "Cow", capital: "Calf", emoji: "🐮", image: "assets/animal-images/04_Cow_Calf.jpg" },
       { name: "Horse", capital: "Foal", emoji: "🐴", image: "assets/animal-images/05_Horse_Foal.jpg" },
       { name: "Duck", capital: "Duckling", emoji: "🦆", image: "assets/animal-images/06_Duck_Duckling.jpg" },
       { name: "Sheep", capital: "Lamb", emoji: "🐑", image: "assets/animal-images/07_Sheep_Lamb.jpg" },
       { name: "Kangaroo", capital: "Joey", emoji: "🦘", image: "assets/animal-images/08_Kangaroo_Joey.jpg" },
       { name: "Pig", capital: "Piglet", emoji: "🐷", image: "assets/animal-images/09_Pig_Piglet.jpg" },
       { name: "Deer", capital: "Fawn", emoji: "🦌", image: "assets/animal-images/10_Deer_Fawn.jpg" },
       { name: "Goat", capital: "Kid", emoji: "🐐", image: "assets/animal-images/11_Goat_Kid.jpg" },
       { name: "Elephant", capital: "Calf", emoji: "🐘", image: "assets/animal-images/12_Elephant_Calf.jpg" },
       { name: "Frog", capital: "Tadpole", emoji: "🐸", image: "assets/animal-images/13_Frog_Tadpole.jpg" },
       { name: "Bear", capital: "Cub", emoji: "🐻", image: "assets/animal-images/14_Bear_Cub.jpg" },
       { name: "Hen", capital: "Chick", emoji: "🐔", image: "assets/animal-images/15_Hen_Chick.jpg" }
     ],
     homes: [
       { name: "Honeybee", capital: "Hive", emoji: "🐝", image: "assets/animal-homes/01_Honeybee_Hive.jpg" },
       { name: "Bird", capital: "Nest", emoji: "🐦", image: "assets/animal-homes/02_Bird_Nest.jpg" },
       { name: "Spider", capital: "Web", emoji: "🕷️", image: "assets/animal-homes/03_Spider_Web.jpg" },
       { name: "Lion", capital: "Den", emoji: "🦁", image: "assets/animal-homes/04_Lion_Den.jpg" },
       { name: "Rabbit", capital: "Burrow", emoji: "🐰", image: "assets/animal-homes/05_Rabbit_Burrow.jpg" },
       { name: "Ant", capital: "Anthill", emoji: "🐜", image: "assets/animal-homes/06_Ant_Anthill.jpg" },
       { name: "Dog", capital: "Kennel", emoji: "🐶", image: "assets/animal-homes/07_Dog_Kennel.jpg" },
       { name: "Horse", capital: "Stable", emoji: "🐴", image: "assets/animal-homes/08_Horse_Stable.jpg" },
       { name: "Fish", capital: "Ocean", emoji: "🐟", image: "assets/animal-homes/09_Fish_Ocean.jpg" },
       { name: "Owl", capital: "Hollow", emoji: "🦉", image: "assets/animal-homes/10_Owl_Hollow.jpg" },
       { name: "Bat", capital: "Cave", emoji: "🦇", image: "assets/animal-homes/11_Bat_Cave.jpg" },
       { name: "Pig", capital: "Sty", emoji: "🐷", image: "assets/animal-homes/12_Pig_Sty.jpg" },
       { name: "Hen", capital: "Coop", emoji: "🐔", image: "assets/animal-homes/13_Hen_Coop.jpg" },
       { name: "Polar Bear", capital: "Ice Cave", emoji: "🧊", image: "assets/animal-homes/14_PolarBear_IceCave.jpg" },
       { name: "Squirrel", capital: "Drey", emoji: "🐿️", image: "assets/animal-homes/15_Squirrel_Drey.jpg" }
     ],
      festivals: [
       { name: "Diwali", capital: "Diwali", hint: "The Festival of Lights", emoji: "🪔", image: "assets/festival-images/01_Diwali.jpg" },
       { name: "Holi", capital: "Holi", hint: "The Festival of Colors", emoji: "🌈", image: "assets/festival-images/02_Holi.jpg" },
       { name: "Ganesh Chaturthi", capital: "Ganesh Chaturthi", hint: "Lord Ganesha's Birthday", emoji: "🐘", image: "assets/festival-images/03_Ganesh_Chaturthi.jpg" },
       { name: "Navratri", capital: "Navratri", hint: "Nine nights of Dancing", emoji: "💃", image: "assets/festival-images/04_Navratri.jpg" },
       { name: "Dussehra", capital: "Dussehra", hint: "Victory of Good over Evil", emoji: "🏹", image: "assets/festival-images/05_Dussehra.jpg" },
       { name: "Raksha Bandhan", capital: "Raksha Bandhan", hint: "A bond between brother and sister", emoji: "🧶", image: "assets/festival-images/06_Raksha_Bandhan.jpg" },
       { name: "Krishna Janmashtami", capital: "Krishna Janmashtami", hint: "Lord Krishna's Birthday", emoji: "🍯", image: "assets/festival-images/07_Krishna_Janmashtami.jpg" },
       { name: "Eid-ul-Fitr", capital: "Eid-ul-Fitr", hint: "End of the holy month of Ramadan", emoji: "🌙", image: "assets/festival-images/08_Eid_ul_Fitr.jpg" },
       { name: "Christmas", capital: "Christmas", hint: "Jesus Christ's Birthday", emoji: "🎄", image: "assets/festival-images/09_Christmas.jpg" },
       { name: "Makar Sankranti", capital: "Makar Sankranti", hint: "Kite flying festival", emoji: "🪁", image: "assets/festival-images/10_Makar_Sankranti.jpg" },
       { name: "Pongal", capital: "Pongal", hint: "Harvest festival of Tamil Nadu", emoji: "🌾", image: "assets/festival-images/11_Pongal.jpg" },
       { name: "Onam", capital: "Onam", hint: "Harvest festival of Kerala", emoji: "🛶", image: "assets/festival-images/12_Onam.jpg" },
       { name: "Baisakhi", capital: "Baisakhi", hint: "Harvest festival of Punjab", emoji: "🚜", image: "assets/festival-images/13_Baisakhi.jpg" },
       { name: "Durga Puja", capital: "Durga Puja", hint: "Victory of Goddess Durga", emoji: "🔱", image: "assets/festival-images/14_Durga_Puja.jpg" },
       { name: "Gudhi Padwa", capital: "Gudhi Padwa", hint: "Marathi New Year", emoji: "🚩", image: "assets/festival-images/15_Gudhi_Padwa.jpg" },
       { name: "Bihu", capital: "Bihu", hint: "Harvest festival of Assam", emoji: "🎻", image: "assets/festival-images/16_Bihu.jpg" },
       { name: "Chhath Puja", capital: "Chhath Puja", hint: "Worship of the Sun God", emoji: "☀️", image: "assets/festival-images/17_Chhath_Puja.jpg" },
       { name: "Guru Nanak Jayanti", capital: "Guru Nanak Jayanti", hint: "Birthday of Guru Nanak Dev Ji", emoji: "🕯️", image: "assets/festival-images/18_Guru_Nanak_Jayanti.jpg" },
       { name: "Mahashivratri", capital: "Mahashivratri", hint: "The Great Night of Lord Shiva", emoji: "🔱", image: "assets/festival-images/19_Mahashivratri.jpg" },
       { name: "Basant Panchami", capital: "Basant Panchami", hint: "Worship of Goddess Saraswati", emoji: "🎻", image: "assets/festival-images/20_Basant_Panchami.jpg" },
       { name: "Karwa Chauth", capital: "Karwa Chauth", hint: "Wives fast for their husbands", emoji: "🥣", image: "assets/festival-images/21_Karwa_Chauth.jpg" },
       { name: "Ram Navami", capital: "Ram Navami", hint: "Lord Rama's Birthday", emoji: "🏹", image: "assets/festival-images/22_Ram_Navami.jpg" },
       { name: "Hanuman Jayanti", capital: "Hanuman Jayanti", hint: "Lord Hanuman's Birthday", emoji: "🐒", image: "assets/festival-images/23_Hanuman_Jayanti.jpg" },
       { name: "Lohri", capital: "Lohri", hint: "Punjabi winter bonfire festival", emoji: "🔥", image: "assets/festival-images/24_Lohri.jpg" },
       { name: "Buddha Purnima", capital: "Buddha Purnima", hint: "Lord Buddha's Birthday", emoji: "☸️", image: "assets/festival-images/25_Buddha_Purnima.jpg" },
       { name: "Mahavir Jayanti", capital: "Mahavir Jayanti", hint: "Lord Mahavir's Birthday", emoji: "🧘", image: "assets/festival-images/26_Mahavir_Jayanti.jpg" },
       { name: "Ugadi", capital: "Ugadi", hint: "New Year in Telugu and Kannada", emoji: "🥭", image: "assets/festival-images/27_Ugadi.jpg" },
       { name: "Vishu", capital: "Vishu", hint: "Malayalam New Year", emoji: "🌼", image: "assets/festival-images/28_Vishu.jpg" },
       { name: "Pana Sankranti", capital: "Pana Sankranti", hint: "Odia New Year", emoji: "🥤", image: "assets/festival-images/29_Pana_Sankranti.jpg" },
       { name: "Poila Baisakh", capital: "Poila Baisakh", hint: "Bengali New Year", emoji: "🥘", image: "assets/festival-images/30_Poila_Baisakh.jpg" },
       { name: "Hemis Festival", capital: "Hemis Festival", hint: "Mask dance festival of Ladakh", emoji: "👺", image: "assets/festival-images/31_Hemis_Festival.jpg" },
       { name: "Hornbill Festival", capital: "Hornbill Festival", hint: "Festival of Festivals in Nagaland", emoji: "🎺", image: "assets/festival-images/32_Hornbill_Festival.jpg" },
       { name: "Rath Yatra", capital: "Rath Yatra", hint: "The Chariot Festival", emoji: "🚜", image: "assets/festival-images/33_Rath_Yatra.jpg" },
       { name: "Kumbh Mela", capital: "Kumbh Mela", hint: "World's largest religious gathering", emoji: "🌊", image: "assets/festival-images/34_Kumbh_Mela.jpg" },
       { name: "Camel Festival", capital: "Camel Festival", hint: "Celebrated in Bikaner", emoji: "🐪", image: "assets/festival-images/35_Camel_Festival.jpg" },
       { name: "Pushkar Fair", capital: "Pushkar Fair", hint: "Famous livestock and camel fair", emoji: "🎡", image: "assets/festival-images/36_Pushkar_Fair.jpg" },
       { name: "Goa Carnival", capital: "Goa Carnival", hint: "Colorful parade and music", emoji: "🎭", image: "assets/festival-images/37_Goa_Carnival.jpg" },
       { name: "Thrissur Pooram", capital: "Thrissur Pooram", hint: "Grand elephant festival", emoji: "🐘", image: "assets/festival-images/38_Thrissur_Pooram.jpg" },
       { name: "Losar", capital: "Losar", hint: "Tibetan New Year", emoji: "🏔️", image: "assets/festival-images/39_Losar.jpg" },
       { name: "Bathukamma", capital: "Bathukamma", hint: "Flower festival of Telangana", emoji: "🌸", image: "assets/festival-images/40_Bathukamma.jpg" }
     ],
     body: [
        { name: "Which organ helps us breathe?", capital: "Lungs", emoji: "🫁", image: "assets/body-images/01_Lungs.jpg" },
        { name: "Which organ pumps blood to our body?", capital: "Heart", emoji: "❤️", image: "assets/body-images/02_Heart.jpg" },
        { name: "Which part helps us think and learn?", capital: "Brain", emoji: "🧠", image: "assets/body-images/03_Brain.jpg" },
        { name: "Which organ helps us digest food?", capital: "Stomach", emoji: "🥣", image: "assets/body-images/04_Stomach.jpg" },
        { name: "Which part of the body helps us see?", capital: "Eyes", emoji: "👀", image: "assets/body-images/05_Eyes.jpg" },
        { name: "Which part helps us hear music and sounds?", capital: "Ears", emoji: "👂", image: "assets/body-images/06_Ears.jpg" },
        { name: "Which part helps us smell flowers?", capital: "Nose", emoji: "👃", image: "assets/body-images/07_Nose.jpg" },
        { name: "Which part helps us taste yummy food?", capital: "Tongue", emoji: "👅", image: "assets/body-images/08_Tongue.jpg" },
        { name: "What covers our whole body and protects it?", capital: "Skin", emoji: "🤚", image: "assets/body-images/09_Skin.jpg" },
        { name: "What are the hard parts that make our frame?", capital: "Bones", emoji: "🦴", image: "assets/body-images/10_Bones.jpg" },
        { name: "Which part helps us chew our food?", capital: "Teeth", emoji: "🦷", image: "assets/body-images/11_Teeth.jpg" },
        { name: "Which part helps us hold and grab things?", capital: "Hands", emoji: "🖐️", image: "assets/body-images/12_Hands.jpg" },
        { name: "Which part helps us walk and run?", capital: "Legs", emoji: "🦵", image: "assets/body-images/13_Legs.jpg" },
        { name: "Which part helps our arms bend?", capital: "Elbow", emoji: "💪", image: "assets/body-images/14_Elbow.jpg" },
        { name: "Which part helps our legs bend?", capital: "Knee", emoji: "🦵", image: "assets/body-images/15_Knee.jpg" }
      ],
      helpers: [
        {"name": "Stethoscope", "capital": "Doctor", "emoji": "🩺", "image": "assets/helper-images/01_Stethoscope.jpg"},
        {"name": "Fire Truck", "capital": "Firefighter", "emoji": "🚒", "image": "assets/helper-images/02_Fire_Truck.jpg"},
        {"name": "Police Car", "capital": "Police Officer", "emoji": "🚓", "image": "assets/helper-images/03_Police_Car.jpg"},
        {"name": "Chalkboard", "capital": "Teacher", "emoji": "🧑‍🏫", "image": "assets/helper-images/04_Chalkboard.jpg"},
        {"name": "Baking Oven", "capital": "Baker", "emoji": "🥯", "image": "assets/helper-images/05_Baking_Oven.jpg"},
        {"name": "Airplane", "capital": "Pilot", "emoji": "✈️", "image": "assets/helper-images/06_Airplane.jpg"},
        {"name": "Mail Bag", "capital": "Postman", "emoji": "📬", "image": "assets/helper-images/07_Mail_Bag.jpg"},
        {"name": "Paint Palette", "capital": "Artist", "emoji": "🎨", "image": "assets/helper-images/08_Paint_Palette.jpg"},
        {"name": "Microscope", "capital": "Scientist", "emoji": "🔬", "image": "assets/helper-images/09_Microscope.jpg"},
        {"name": "Wrench", "capital": "Mechanic", "emoji": "🔧", "image": "assets/helper-images/10_Wrench.jpg"},
        {"name": "Spaceship", "capital": "Astronaut", "emoji": "🚀", "image": "assets/helper-images/11_Spaceship.jpg"},
        {"name": "Frying Pan", "capital": "Chef", "emoji": "🍳", "image": "assets/helper-images/12_Frying_Pan.jpg"},
        {"name": "Gardening Hoe", "capital": "Gardener", "emoji": "🪴", "image": "assets/helper-images/13_Gardening_Hoe.jpg"},
        {"name": "Library Books", "capital": "Librarian", "emoji": "📚", "image": "assets/helper-images/14_Library_Books.jpg"},
        {"name": "Bus", "capital": "Bus Driver", "emoji": "🚌", "image": "assets/helper-images/15_Bus.jpg"},
        {"name": "Tractor", "capital": "Farmer", "emoji": "🚜", "image": "assets/helper-images/16_Tractor.jpg"},
        {"name": "Thermometer", "capital": "Nurse", "emoji": "🌡️", "image": "assets/helper-images/17_Thermometer.jpg"},
        {"name": "Hammer", "capital": "Carpenter", "emoji": "🔨", "image": "assets/helper-images/18_Hammer.jpg"},
        {"name": "Whistle", "capital": "Coach", "emoji": "📢", "image": "assets/helper-images/19_Whistle.jpg"},
        {"name": "Microphone", "capital": "Singer", "emoji": "🎤", "image": "assets/helper-images/20_Microphone.jpg"},
        {"name": "Camera", "capital": "Photographer", "emoji": "📷", "image": "assets/helper-images/21_Camera.jpg"},
        {"name": "Computer", "capital": "Programmer", "emoji": "💻", "image": "assets/helper-images/22_Computer.jpg"},
        {"name": "Sewing Machine", "capital": "Tailor", "emoji": "🧵", "image": "assets/helper-images/23_Sewing_Machine.jpg"},
        {"name": "Trash Truck", "capital": "Sanitation Worker", "emoji": "🚛", "image": "assets/helper-images/24_Trash_Truck.jpg"},
        {"name": "Dental Mirror", "capital": "Dentist", "emoji": "🦷", "image": "assets/helper-images/25_Dental_Mirror.jpg"}
      ],
materials: [
         {"name": "Key", "capital": "Metal", "emoji": "🔑", "image": "assets/material-images/01_Key.jpg"},
         {"name": "Water Bottle", "capital": "Plastic", "emoji": "🧴", "image": "assets/material-images/02_Water_Bottle.jpg"},
         {"name": "Window", "capital": "Glass", "emoji": "🪟", "image": "assets/material-images/03_Window.jpg"},
         {"name": "Table", "capital": "Wood", "emoji": "🪑", "image": "assets/material-images/04_Table.jpg"},
         {"name": "Teddy Bear", "capital": "Fabric", "emoji": "🧸", "image": "assets/material-images/05_Teddy_Bear.jpg"},
         {"name": "Spoon", "capital": "Metal", "emoji": "🥄", "image": "assets/material-images/06_Spoon.jpg"},
         {"name": "Pencil", "capital": "Wood", "emoji": "✏️", "image": "assets/material-images/07_Pencil.jpg"},
         {"name": "Drinking Glass", "capital": "Glass", "emoji": "🥛", "image": "assets/material-images/08_Drinking_Glass.jpg"},
         {"name": "T-shirt", "capital": "Fabric", "emoji": "👕", "image": "assets/material-images/09_Tshirt.jpg"},
         {"name": "Toy Car", "capital": "Plastic", "emoji": "🏎️", "image": "assets/material-images/10_Toy_Car.jpg"},
         {"name": "Hammer", "capital": "Metal", "emoji": "🔨", "image": "assets/material-images/11_Hammer.jpg"},
         {"name": "Door", "capital": "Wood", "emoji": "🚪", "image": "assets/material-images/12_Door.jpg"},
         {"name": "Eyeglasses", "capital": "Glass", "emoji": "👓", "image": "assets/material-images/13_Eyeglasses.jpg"},
         {"name": "Pillow", "capital": "Fabric", "emoji": "🛌", "image": "assets/material-images/14_Pillow.jpg"},
         {"name": "Lunch Box", "capital": "Plastic", "emoji": "🍱", "image": "assets/material-images/15_Lunch_Box.jpg"},
         {"name": "Coin", "capital": "Metal", "emoji": "🪙", "image": "assets/material-images/16_Coin.jpg"},
         {"name": "Bat", "capital": "Wood", "emoji": "🏏", "image": "assets/material-images/17_Bat.jpg"},
         {"name": "Mirror", "capital": "Glass", "emoji": "🪞", "image": "assets/material-images/18_Mirror.jpg"},
         {"name": "Curtains", "capital": "Fabric", "emoji": "カーテン", "image": "assets/material-images/19_Curtains.jpg"},
         {"name": "Straw", "capital": "Plastic", "emoji": "🥤", "image": "assets/material-images/20_Straw.jpg"},
         {"name": "Bicycle", "capital": "Metal", "emoji": "🚲", "image": "assets/material-images/21_Bicycle.jpg"},
         {"name": "Fence", "capital": "Wood", "emoji": "🪵", "image": "assets/material-images/22_Fence.jpg"},
         {"name": "Lightbulb", "capital": "Glass", "emoji": "💡", "image": "assets/material-images/23_Lightbulb.jpg"},
         {"name": "Socks", "capital": "Fabric", "emoji": "🧦", "image": "assets/material-images/24_Socks.jpg"},
         {"name": "Bucket", "capital": "Plastic", "emoji": "🪣", "image": "assets/material-images/25_Bucket.jpg"}
       ],

      countries: [
        { "name": "Afghanistan", "capital": "Kabul", "phonetic": "Afghanistan" },
        { "name": "Albania", "capital": "Tirana", "phonetic": "Albania" },
        { "name": "Algeria", "capital": "Algiers", "phonetic": "Algeria" },
        { "name": "Andorra", "capital": "Andorra la Vella", "phonetic": "Andorra" },
        { "name": "Angola", "capital": "Luanda", "phonetic": "Angola" },
        { "name": "Antigua and Barbuda", "capital": "Saint John's", "phonetic": "Antigua and Barbuda" },
        { "name": "Argentina", "capital": "Buenos Aires", "phonetic": "Argentina" },
        { "name": "Armenia", "capital": "Yerevan", "phonetic": "Armenia" },
        { "name": "Australia", "capital": "Canberra", "phonetic": "Australia" },
        { "name": "Austria", "capital": "Vienna", "phonetic": "Austria" },
        { "name": "Azerbaijan", "capital": "Baku", "phonetic": "Azerbaijan" },
        { "name": "Bahamas", "capital": "Nassau", "phonetic": "Bahamas" },
        { "name": "Bahrain", "capital": "Manama", "phonetic": "Bahrain" },
        { "name": "Bangladesh", "capital": "Dhaka", "phonetic": "Bangladesh" },
        { "name": "Barbados", "capital": "Bridgetown", "phonetic": "Barbados" },
        { "name": "Belarus", "capital": "Minsk", "phonetic": "Belarus" },
        { "name": "Belgium", "capital": "Brussels", "phonetic": "Belgium" },
        { "name": "Belize", "capital": "Belmopan", "phonetic": "Belize" },
        { "name": "Benin", "capital": "Porto-Novo", "phonetic": "Benin" },
        { "name": "Bhutan", "capital": "Thimphu", "phonetic": "Bhutan" },
        { "name": "Bolivia", "capital": "Sucre", "phonetic": "Bolivia" },
        { "name": "Bosnia and Herzegovina", "capital": "Sarajevo", "phonetic": "Bosnia and Herzegovina" },
        { "name": "Botswana", "capital": "Gaborone", "phonetic": "Botswana" },
        { "name": "Brazil", "capital": "Brasilia", "phonetic": "Brazil" },
        { "name": "Brunei", "capital": "Bandar Seri Begawan", "phonetic": "Brunei" },
        { "name": "Bulgaria", "capital": "Sofia", "phonetic": "Bulgaria" },
        { "name": "Burkina Faso", "capital": "Ouagadougou", "phonetic": "Burkina Faso" },
        { "name": "Burundi", "capital": "Gitega", "phonetic": "Burundi" },
        { "name": "Cabo Verde", "capital": "Praia", "phonetic": "Cabo Verde" },
        { "name": "Cambodia", "capital": "Phnom Penh", "phonetic": "Cambodia" },
        { "name": "Cameroon", "capital": "Yaounde", "phonetic": "Cameroon" },
        { "name": "Canada", "capital": "Ottawa", "phonetic": "Canada" },
        { "name": "Central African Republic", "capital": "Bangui", "phonetic": "Central African Republic" },
        { "name": "Chad", "capital": "N'Djamena", "phonetic": "Chad" },
        { "name": "Chile", "capital": "Santiago", "phonetic": "Chile" },
        { "name": "China", "capital": "Beijing", "phonetic": "China" },
        { "name": "Colombia", "capital": "Bogota", "phonetic": "Colombia" },
        { "name": "Comoros", "capital": "Moroni", "phonetic": "Comoros" },
        { "name": "Congo (Congo-Brazzaville)", "capital": "Brazzaville", "phonetic": "Congo" },
        { "name": "Costa Rica", "capital": "San Jose", "phonetic": "Costa Rica" },
        { "name": "Croatia", "capital": "Zagreb", "phonetic": "Croatia" },
        { "name": "Cuba", "capital": "Havana", "phonetic": "Cuba" },
        { "name": "Cyprus", "capital": "Nicosia", "phonetic": "Cyprus" },
        { "name": "Czechia (Czech Republic)", "capital": "Prague", "phonetic": "Czechia" },
        { "name": "Democratic Republic of the Congo", "capital": "Kinshasa", "phonetic": "Democratic Republic of the Congo" },
        { "name": "Denmark", "capital": "Copenhagen", "phonetic": "Denmark" },
        { "name": "Djibouti", "capital": "Djibouti", "phonetic": "Djibouti" },
        { "name": "Dominica", "capital": "Roseau", "phonetic": "Dominica" },
        { "name": "Dominican Republic", "capital": "Santo Domingo", "phonetic": "Dominican Republic" },
        { "name": "Ecuador", "capital": "Quito", "phonetic": "Ecuador" },
        { "name": "Egypt", "capital": "Cairo", "phonetic": "Egypt" },
        { "name": "El Salvador", "capital": "San Salvador", "phonetic": "El Salvador" },
        { "name": "Equatorial Guinea", "capital": "Malabo", "phonetic": "Equatorial Guinea" },
        { "name": "Eritrea", "capital": "Asmara", "phonetic": "Eritrea" },
        { "name": "Estonia", "capital": "Tallinn", "phonetic": "Estonia" },
        { "name": "Eswatini", "capital": "Mbabane", "phonetic": "Eswatini" },
        { "name": "Ethiopia", "capital": "Addis Ababa", "phonetic": "Ethiopia" },
        { "name": "Fiji", "capital": "Suva", "phonetic": "Fiji" },
        { "name": "Finland", "capital": "Helsinki", "phonetic": "Finland" },
        { "name": "France", "capital": "Paris", "phonetic": "France" },
        { "name": "Gabon", "capital": "Libreville", "phonetic": "Gabon" },
        { "name": "Gambia", "capital": "Banjul", "phonetic": "Gambia" },
        { "name": "Georgia", "capital": "Tbilisi", "phonetic": "Georgia" },
        { "name": "Germany", "capital": "Berlin", "phonetic": "Germany" },
        { "name": "Ghana", "capital": "Accra", "phonetic": "Ghana" },
        { "name": "Greece", "capital": "Athens", "phonetic": "Greece" },
        { "name": "Grenada", "capital": "Saint George's", "phonetic": "Grenada" },
        { "name": "Guatemala", "capital": "Guatemala City", "phonetic": "Guatemala" },
        { "name": "Guinea", "capital": "Conakry", "phonetic": "Guinea" },
        { "name": "Guinea-Bissau", "capital": "Bissau", "phonetic": "Guinea Bissau" },
        { "name": "Guyana", "capital": "Georgetown", "phonetic": "Guyana" },
        { "name": "Haiti", "capital": "Port-au-Prince", "phonetic": "Haiti" },
        { "name": "Honduras", "capital": "Tegucigalpa", "phonetic": "Honduras" },
        { "name": "Hungary", "capital": "Budapest", "phonetic": "Hungary" },
        { "name": "Iceland", "capital": "Reykjavik", "phonetic": "Iceland" },
        { "name": "India", "capital": "New Delhi", "phonetic": "India" },
        { "name": "Indonesia", "capital": "Jakarta", "phonetic": "Indonesia" },
        { "name": "Iran", "capital": "Tehran", "phonetic": "Iran" },
        { "name": "Iraq", "capital": "Baghdad", "phonetic": "Iraq" },
        { "name": "Ireland", "capital": "Dublin", "phonetic": "Ireland" },
        { "name": "Israel", "capital": "Jerusalem", "phonetic": "Israel" },
        { "name": "Italy", "capital": "Rome", "phonetic": "Italy" },
        { "name": "Ivory Coast", "capital": "Yamoussoukro", "phonetic": "Ivory Coast" },
        { "name": "Jamaica", "capital": "Kingston", "phonetic": "Jamaica" },
        { "name": "Japan", "capital": "Tokyo", "phonetic": "Japan" },
        { "name": "Jordan", "capital": "Amman", "phonetic": "Jordan" },
        { "name": "Kazakhstan", "capital": "Astana", "phonetic": "Kazakhstan" },
        { "name": "Kenya", "capital": "Nairobi", "phonetic": "Kenya" },
        { "name": "Kiribati", "capital": "Tarawa", "phonetic": "Kiribati" },
        { "name": "Kuwait", "capital": "Kuwait City", "phonetic": "Kuwait" },
        { "name": "Kyrgyzstan", "capital": "Bishkek", "phonetic": "Kyrgyzstan" },
        { "name": "Laos", "capital": "Vientiane", "phonetic": "Laos" },
        { "name": "Latvia", "capital": "Riga", "phonetic": "Latvia" },
        { "name": "Lebanon", "capital": "Beirut", "phonetic": "Lebanon" },
        { "name": "Lesotho", "capital": "Maseru", "phonetic": "Lesotho" },
        { "name": "Liberia", "capital": "Monrovia", "phonetic": "Liberia" },
        { "name": "Libya", "capital": "Tripoli", "phonetic": "Libya" },
        { "name": "Liechtenstein", "capital": "Vaduz", "phonetic": "Liechtenstein" },
        { "name": "Lithuania", "capital": "Vilnius", "phonetic": "Lithuania" },
        { "name": "Luxembourg", "capital": "Luxembourg", "phonetic": "Luxembourg" },
        { "name": "Madagascar", "capital": "Antananarivo", "phonetic": "Madagascar" },
        { "name": "Malawi", "capital": "Lilongwe", "phonetic": "Malawi" },
        { "name": "Malaysia", "capital": "Kuala Lumpur", "phonetic": "Malaysia" },
        { "name": "Maldives", "capital": "Male", "phonetic": "Maldives" },
        { "name": "Mali", "capital": "Bamako", "phonetic": "Mali" },
        { "name": "Malta", "capital": "Valletta", "phonetic": "Malta" },
        { "name": "Marshall Islands", "capital": "Majuro", "phonetic": "Marshall Islands" },
        { "name": "Mauritania", "capital": "Nouakchott", "phonetic": "Mauritania" },
        { "name": "Mauritius", "capital": "Port Louis", "phonetic": "Mauritius" },
        { "name": "Mexico", "capital": "Mexico City", "phonetic": "Mexico" },
        { "name": "Micronesia", "capital": "Palikir", "phonetic": "Micronesia" },
        { "name": "Moldova", "capital": "Chisinau", "phonetic": "Moldova" },
        { "name": "Monaco", "capital": "Monaco", "phonetic": "Monaco" },
        { "name": "Mongolia", "capital": "Ulaanbaatar", "phonetic": "Mongolia" },
        { "name": "Montenegro", "capital": "Podgorica", "phonetic": "Montenegro" },
        { "name": "Morocco", "capital": "Rabat", "phonetic": "Morocco" },
        { "name": "Mozambique", "capital": "Maputo", "phonetic": "Mozambique" },
        { "name": "Myanmar (Burma)", "capital": "Naypyidaw", "phonetic": "Myanmar" },
        { "name": "Namibia", "capital": "Windhoek", "phonetic": "Namibia" },
        { "name": "Nauru", "capital": "Yaren", "phonetic": "Nauru" },
        { "name": "Nepal", "capital": "Kathmandu", "phonetic": "Nepal" },
        { "name": "Netherlands", "capital": "Amsterdam", "phonetic": "Netherlands" },
        { "name": "New Zealand", "capital": "Wellington", "phonetic": "New Zealand" },
        { "name": "Nicaragua", "capital": "Managua", "phonetic": "Nicaragua" },
        { "name": "Niger", "capital": "Niamey", "phonetic": "Niger" },
        { "name": "Nigeria", "capital": "Abuja", "phonetic": "Nigeria" },
        { "name": "North Korea", "capital": "Pyongyang", "phonetic": "North Korea" },
        { "name": "North Macedonia", "capital": "Skopje", "phonetic": "North Macedonia" },
        { "name": "Norway", "capital": "Oslo", "phonetic": "Norway" },
        { "name": "Oman", "capital": "Muscat", "phonetic": "Oman" },
        { "name": "Pakistan", "capital": "Islamabad", "phonetic": "Pakistan" },
        { "name": "Palau", "capital": "Ngerulmud", "phonetic": "Palau" },
        { "name": "Palestine", "capital": "Jerusalem", "phonetic": "Palestine" },
        { "name": "Panama", "capital": "Panama City", "phonetic": "Panama" },
        { "name": "Papua New Guinea", "capital": "Port Moresby", "phonetic": "Papua New Guinea" },
        { "name": "Paraguay", "capital": "Asuncion", "phonetic": "Paraguay" },
        { "name": "Peru", "capital": "Lima", "phonetic": "Peru" },
        { "name": "Philippines", "capital": "Manila", "phonetic": "Philippines" },
        { "name": "Poland", "capital": "Warsaw", "phonetic": "Poland" },
        { "name": "Portugal", "capital": "Lisbon", "phonetic": "Portugal" },
        { "name": "Qatar", "capital": "Doha", "phonetic": "Qatar" },
        { "name": "Romania", "capital": "Bucharest", "phonetic": "Romania" },
        { "name": "Russia", "capital": "Moscow", "phonetic": "Russia" },
        { "name": "Rwanda", "capital": "Kigali", "phonetic": "Rwanda" },
        { "name": "Saint Kitts and Nevis", "capital": "Basseterre", "phonetic": "Saint Kitts and Nevis" },
        { "name": "Saint Lucia", "capital": "Castries", "phonetic": "Saint Lucia" },
        { "name": "Saint Vincent and the Grenadines", "capital": "Kingstown", "phonetic": "Saint Vincent and the Grenadines" },
        { "name": "Samoa", "capital": "Apia", "phonetic": "Samoa" },
        { "name": "San Marino", "capital": "San Marino", "phonetic": "San Marino" },
        { "name": "Sao Tome and Principe", "capital": "Sao Tome", "phonetic": "Sao Tome and Principe" },
        { "name": "Saudi Arabia", "capital": "Riyadh", "phonetic": "Saudi Arabia" },
        { "name": "Senegal", "capital": "Dakar", "phonetic": "Senegal" },
        { "name": "Serbia", "capital": "Belgrade", "phonetic": "Serbia" },
        { "name": "Seychelles", "capital": "Victoria", "phonetic": "Seychelles" },
        { "name": "Sierra Leone", "capital": "Freetown", "phonetic": "Sierra Leone" },
        { "name": "Singapore", "capital": "Singapore", "phonetic": "Singapore" },
        { "name": "Slovakia", "capital": "Bratislava", "phonetic": "Slovakia" },
        { "name": "Slovenia", "capital": "Ljubljana", "phonetic": "Slovenia" },
        { "name": "Solomon Islands", "capital": "Honiara", "phonetic": "Solomon Islands" },
        { "name": "Somalia", "capital": "Mogadishu", "phonetic": "Somalia" },
        { "name": "South Africa", "capital": "Pretoria", "phonetic": "South Africa" },
        { "name": "South Korea", "capital": "Seoul", "phonetic": "South Korea" },
        { "name": "South Sudan", "capital": "Juba", "phonetic": "South Sudan" },
        { "name": "Spain", "capital": "Madrid", "phonetic": "Spain" },
        { "name": "Sri Lanka", "capital": "Sri Jayawardenepura Kotte", "phonetic": "Sri Lanka" },
        { "name": "Sudan", "capital": "Khartoum", "phonetic": "Sudan" },
        { "name": "Suriname", "capital": "Paramaribo", "phonetic": "Suriname" },
        { "name": "Sweden", "capital": "Stockholm", "phonetic": "Sweden" },
        { "name": "Switzerland", "capital": "Bern", "phonetic": "Switzerland" },
        { "name": "Syria", "capital": "Damascus", "phonetic": "Syria" },
        { "name": "Taiwan", "capital": "Taipei", "phonetic": "Taiwan" },
        { "name": "Tajikistan", "capital": "Dushanbe", "phonetic": "Tajikistan" },
        { "name": "Tanzania", "capital": "Dodoma", "phonetic": "Tanzania" },
        { "name": "Thailand", "capital": "Bangkok", "phonetic": "Thailand" },
        { "name": "Timor-Leste", "capital": "Dili", "phonetic": "Timor Leste" },
        { "name": "Togo", "capital": "Lome", "phonetic": "Togo" },
        { "name": "Tonga", "capital": "Nuku'alofa", "phonetic": "Tonga" },
        { "name": "Trinidad and Tobago", "capital": "Port of Spain", "phonetic": "Trinidad and Tobago" },
        { "name": "Tunisia", "capital": "Tunis", "phonetic": "Tunisia" },
        { "name": "Turkey", "capital": "Ankara", "phonetic": "Turkey" },
        { "name": "Turkmenistan", "capital": "Ashgabat", "phonetic": "Turkmenistan" },
        { "name": "Tuvalu", "capital": "Funafuti", "phonetic": "Tuvalu" },
        { "name": "Uganda", "capital": "Kampala", "phonetic": "Uganda" },
        { "name": "Ukraine", "capital": "Kyiv", "phonetic": "Ukraine" },
        { "name": "United Arab Emirates", "capital": "Abu Dhabi", "phonetic": "United Arab Emirates" },
        { "name": "United Kingdom", "capital": "London", "phonetic": "United Kingdom" },
        { "name": "United States of America", "capital": "Washington, D.C.", "phonetic": "United States of America" },
        { "name": "Uruguay", "capital": "Montevideo", "phonetic": "Uruguay" },
        { "name": "Uzbekistan", "capital": "Tashkent", "phonetic": "Uzbekistan" },
        { "name": "Vanuatu", "capital": "Port Vila", "phonetic": "Vanuatu" },
        { "name": "Vatican City", "capital": "Vatican City", "phonetic": "Vatican City" },
        { "name": "Venezuela", "capital": "Caracas", "phonetic": "Venezuela" },
        { "name": "Vietnam", "capital": "Hanoi", "phonetic": "Vietnam" },
        { "name": "Yemen", "capital": "Sana'a", "phonetic": "Yemen" },
        { "name": "Zambia", "capital": "Lusaka", "phonetic": "Zambia" },
        { "name": "Zimbabwe", "capital": "Harare", "phonetic": "Zimbabwe" }
      ]
     }
