const QUIZ_DATA = {
    states: [
      { name: "Andhra Pradesh", capital: "Amaravati", phonetic: "Andhra Pradesh" },
      { name: "Arunachal Pradesh", capital: "Itanagar", phonetic: "Arunachal Pradesh" },
      { name: "Assam", capital: "Dispur", phonetic: "Assam" },
      { name: "Bihar", capital: "Patna", phonetic: "Bihar" },
      { name: "Chhattisgarh", capital: "Raipur", phonetic: "Chhattisgarh" },
      { name: "Goa", capital: "Panaji", phonetic: "Goa" },
      { name: "Gujarat", capital: "Gandhinagar", phonetic: "Gujarat" },
      { name: "Haryana", capital: "Chandigarh", phonetic: "Haryana" },
      { name: "Himachal Pradesh", capital: "Shimla", phonetic: "Himachal Pradesh" },
      { name: "Jharkhand", capital: "Ranchi", phonetic: "Jharkhand" },
      { name: "Karnataka", capital: "Bengaluru", phonetic: "Karnataka" },
      { name: "Kerala", capital: "Thiruvananthapuram", phonetic: "Kerala" },
      { name: "Madhya Pradesh", capital: "Bhopal", phonetic: "Madhya Pradesh" },
      { name: "Maharashtra", capital: "Mumbai", phonetic: "Maharashtra" },
      { name: "Manipur", capital: "Imphal", phonetic: "Manipur" },
      { name: "Meghalaya", capital: "Shillong", phonetic: "Meghalaya" },
      { name: "Mizoram", capital: "Aizawl", phonetic: "Mizoram" },
      { name: "Nagaland", capital: "Kohima", phonetic: "Nagaland" },
      { name: "Odisha", capital: "Bhubaneswar", phonetic: "Odisha" },
      { name: "Punjab", capital: "Chandigarh", phonetic: "Punjab" },
      { name: "Rajasthan", capital: "Jaipur", phonetic: "Rajasthan" },
      { name: "Sikkim", capital: "Gangtok", phonetic: "Sikkim" },
      { name: "Tamil Nadu", capital: "Chennai", phonetic: "Tamil Nadu" },
      { name: "Telangana", capital: "Hyderabad", phonetic: "Telangana" },
      { name: "Tripura", capital: "Agartala", phonetic: "Tripura" },
      { name: "Uttarakhand", capital: "Dehradun", phonetic: "Uttarakhand" },
      { name: "Uttar Pradesh", capital: "Lucknow", phonetic: "Uttar Pradesh" },
      { name: "West Bengal", capital: "Kolkata", phonetic: "West Bengal" }
    ],

    uts: [
      { name: "Andaman and Nicobar Islands", capital: "Port Blair", phonetic: "Andaman and Nicobar Islands" },
      { name: "Chandigarh", capital: "Chandigarh", phonetic: "Chandigarh" },
      { name: "Dadra and Nagar Haveli and Daman and Diu", capital: "Daman", phonetic: "Dadra and Nagar Haveli and Daman and Diu" },
      { name: "Delhi", capital: "New Delhi", phonetic: "Delhi" },
      { name: "Jammu and Kashmir", capital: "Srinagar", phonetic: "Jammu and Kashmir" },
      { name: "Ladakh", capital: "Leh", phonetic: "Ladakh" },
      { name: "Lakshadweep", capital: "Kavaratti", phonetic: "Lakshadweep" },
      { name: "Puducherry", capital: "Puducherry", phonetic: "Puducherry" }
    ],
    math: Array.from({ length: 20 }, (_, i) => {
        const a = Math.floor(Math.random() * 9) + 1;
        const b = Math.floor(Math.random() * 9) + 1;
        const fruits = ['🍎', '🍊', '🍌', '🍇', '🍓', '🥭'];
        const fruit = fruits[Math.floor(Math.random() * fruits.length)];
        return {
            num1: a,
            num2: b,
            capital: (a + b).toString(),
            name: `${a} + ${b}`,
            fruit: fruit
        };
    }),
    subtraction: Array.from({ length: 20 }, (_, i) => {
        const a = Math.floor(Math.random() * 9) + 1;
        const b = Math.floor(Math.random() * a) + 1;
        const fruits = ['🍎', '🍊', '🍌', '🍇', '🍓', '🥭'];
        const fruit = fruits[Math.floor(Math.random() * fruits.length)];
        return {
            num1: a,
            num2: b,
            capital: (a - b).toString(),
            name: `${a} - ${b}`,
            fruit: fruit
        };
    }),
    monuments: [
        { name: "Taj Mahal", capital: "Agra", phonetic: "Taj Mahal", image: "assets/monument-images/01_Taj_Mahal.jpg" },
        { name: "Hawa Mahal", capital: "Jaipur", phonetic: "Hawa Mahal", image: "assets/monument-images/02_Hawa_Mahal.jpg" },
        { name: "Gateway of India", capital: "Mumbai", phonetic: "Gateway of India", image: "assets/monument-images/03_Gateway_of_India.jpg" },
        { name: "Golden Temple", capital: "Amritsar", phonetic: "Golden Temple", image: "assets/monument-images/04_Golden_Temple.jpg" },
        { name: "Qutub Minar", capital: "Delhi", phonetic: "Qutub Minar", image: "assets/monument-images/05_Qutub_Minar.jpg" },
        { name: "Charminar", capital: "Hyderabad", phonetic: "Charminar", image: "assets/monument-images/06_Charminar.jpg" },
        { name: "Victoria Memorial", capital: "Kolkata", phonetic: "Victoria Memorial", image: "assets/monument-images/07_Victoria_Memorial.jpg" },
        { name: "Amer Fort", capital: "Jaipur", phonetic: "Amer Fort", image: "assets/monument-images/08_Amer_Fort.jpg" },
        { name: "Lotus Temple", capital: "Delhi", phonetic: "Lotus Temple", image: "assets/monument-images/09_Lotus_Temple.jpg" },
        { name: "Red Fort", capital: "Delhi", phonetic: "Red Fort", image: "assets/monument-images/10_Red_Fort.jpg" },
        { name: "India Gate", capital: "Delhi", phonetic: "India Gate", image: "assets/monument-images/11_India_Gate.jpg" },
        { name: "Mysore Palace", capital: "Mysuru", phonetic: "Mysore Palace", image: "assets/monument-images/12_Mysore_Palace.jpg" },
        { name: "Konark Sun Temple", capital: "Konark", phonetic: "Konark Sun Temple", image: "assets/monument-images/13_Konark_Sun_Temple.jpg" },
        { name: "Ajanta Caves", capital: "Chhatrapati Sambhajinagar", phonetic: "Ajanta Caves", image: "assets/monument-images/14_Ajanta_Caves.jpg" },
        { name: "Meenakshi Temple", capital: "Madurai", phonetic: "Meenakshi Temple", image: "assets/monument-images/15_Meenakshi_Temple.jpg" },
        { name: "Vivekananda Rock", capital: "Kanyakumari", phonetic: "Vivekananda Rock", image: "assets/monument-images/16_Vivekananda_Rock.jpg" },
        { name: "Gol Gumbaz", capital: "Bijapur", phonetic: "Gol Gumbaz", image: "assets/monument-images/17_Gol_Gumbaz.jpg" },
        { name: "Jantar Mantar", capital: "Jaipur", phonetic: "Jantar Mantar", image: "assets/monument-images/18_Jantar_Mantar.jpg" },
        { name: "Chhatrapati Shivaji Terminus", capital: "Mumbai", phonetic: "Chhatrapati Shivaji Terminus", image: "assets/monument-images/19_CST_Mumbai.jpg" },
        { name: "Sanchi Stupa", capital: "Sanchi", phonetic: "Sanchi Stupa", image: "assets/monument-images/20_Sanchi_Stupa.jpg" },

        { name: "Ellora Caves", capital: "Chhatrapati Sambhajinagar", phonetic: "Ellora Caves", image: "assets/monument-images/21_Ellora_Caves.png" },
        { name: "Brihadeeswara Temple", capital: "Thanjavur", phonetic: "Brihadeeswara Temple", image: "assets/monument-images/22_Brihadeeswara_Temple.png" },
        { name: "Khajuraho Temples", capital: "Khajuraho", phonetic: "Khajuraho Temples", image: "assets/monument-images/23_Khajuraho_Temples.png" },
        { name: "Rani ki Vav", capital: "Patan", phonetic: "Rani ki Vav", image: "assets/monument-images/24_Rani_ki_Vav.png" },
        { name: "Fatehpur Sikri", capital: "Fatehpur Sikri", phonetic: "Fatehpur Sikri", image: "assets/monument-images/25_Fatehpur_Sikri.png" },
        { name: "Humayun's Tomb", capital: "Delhi", phonetic: "Humayun's Tomb", image: "assets/monument-images/26_Humayuns_Tomb.png" },
        { name: "Akshardham Temple", capital: "Delhi", phonetic: "Akshardham Temple", image: "assets/monument-images/27_Akshardham_Temple.png" },
        { name: "Somnath Temple", capital: "Somnath", phonetic: "Somnath Temple", image: "assets/monument-images/28_Somnath_Temple.png" },
        { name: "Mahabodhi Temple", capital: "Bodh Gaya", phonetic: "Mahabodhi Temple", image: "assets/monument-images/29_Mahabodhi_Temple.png" },
        { name: "Hampi Ruins", capital: "Hampi", phonetic: "Hampi Ruins", image: "assets/monument-images/30_Hampi_Ruins.png" },
        { name: "Gwalior Fort", capital: "Gwalior", phonetic: "Gwalior Fort", image: "assets/monument-images/31_Gwalior_Fort.png" },
        { name: "Mehrangarh Fort", capital: "Jodhpur", phonetic: "Mehrangarh Fort", image: "assets/monument-images/32_Mehrangarh_Fort.png" },
        { name: "City Palace Udaipur", capital: "Udaipur", phonetic: "City Palace Udaipur", image: "assets/monument-images/33_City_Palace_Udaipur.png" },
        { name: "Lake Palace", capital: "Udaipur", phonetic: "Lake Palace", image: "assets/monument-images/34_Lake_Palace.png" },
        { name: "Nalanda University Ruins", capital: "Nalanda", phonetic: "Nalanda University Ruins", image: "assets/monument-images/35_Nalanda_Ruins.png" },
        { name: "Elephanta Caves", capital: "Mumbai", phonetic: "Elephanta Caves", image: "assets/monument-images/36_Elephanta_Caves.png" },
        { name: "Shaniwar Wada", capital: "Pune", phonetic: "Shaniwar Wada", image: "assets/monument-images/37_Shaniwar_Wada.png" },
        { name: "Agra Fort", capital: "Agra", phonetic: "Agra Fort", image: "assets/monument-images/38_Agra_Fort.png" },
        { name: "Safdarjung Tomb", capital: "Delhi", phonetic: "Safdarjung Tomb", image: "assets/monument-images/39_Safdarjung_Tomb.png" },
        { name: "Purana Qila", capital: "Delhi", phonetic: "Purana Qila", image: "assets/monument-images/40_Purana_Qila.png" },
        { name: "Lingaraj Temple", capital: "Bhubaneswar", phonetic: "Lingaraj Temple", image: "assets/monument-images/41_Lingaraj_Temple.png" },
        { name: "Jagannath Temple", capital: "Puri", phonetic: "Jagannath Temple", image: "assets/monument-images/42_Jagannath_Temple.png" },
        { name: "Padmanabhaswamy Temple", capital: "Thiruvananthapuram", phonetic: "Padmanabhaswamy Temple", image: "assets/monument-images/43_Padmanabhaswamy_Temple.png" },
        { name: "Bekal Fort", capital: "Kasaragod", phonetic: "Bekal Fort", image: "assets/monument-images/44_Bekal_Fort.png" },
        { name: "Chittorgarh Fort", capital: "Chittorgarh", phonetic: "Chittorgarh Fort", image: "assets/monument-images/45_Chittorgarh_Fort.png" },
        { name: "Ranthambore Fort", capital: "Sawai Madhopur", phonetic: "Ranthambore Fort", image: "assets/monument-images/46_Ranthambore_Fort.png" },
        { name: "Tawang Monastery", capital: "Tawang", phonetic: "Tawang Monastery", image: "assets/monument-images/47_Tawang_Monastery.png" },
        { name: "Rumtek Monastery", capital: "Gangtok", phonetic: "Rumtek Monastery", image: "assets/monument-images/48_Rumtek_Monastery.png" },
        { name: "Udayagiri Caves", capital: "Vidisha", phonetic: "Udayagiri Caves", image: "assets/monument-images/49_Udayagiri_Caves.png" },
        { name: "Barabar Caves", capital: "Jehanabad", phonetic: "Barabar Caves", image: "assets/monument-images/50_Barabar_Caves.png" }

    ],
    symbols: [
      { name: "National Animal", capital: "Tiger", category: "animal", emoji: "🐅" },
      { name: "National Bird", capital: "Peacock", category: "bird", emoji: "🦚" },
      { name: "National Fruit", capital: "Mango", category: "fruit", emoji: "🥭" },
      { name: "National Flower", capital: "Lotus", category: "flower", emoji: "🪷" },
      { name: "National Tree", capital: "Banyan Tree", category: "tree", emoji: "🌳" },
      { name: "National River", capital: "Ganga", category: "river", emoji: "🌊" },
      { name: "National Aquatic Animal", capital: "Dolphin", category: "aquatic animal", emoji: "🐬" },
      { name: "National Heritage Animal", capital: "Elephant", category: "heritage animal", emoji: "🐘" },
      { name: "National Game", capital: "Hockey", category: "game", emoji: "🏑" },
      { name: "National Motto", capital: "Satyameva Jayate", category: "motto", emoji: "🇮🇳" },
      { name: "National Reptile", capital: "King Cobra", category: "reptile", emoji: "🐍" },
      { name: "National Microbe", capital: "Lactobacillus", category: "microbe", emoji: "🥛" },
      { name: "National Vegetable", capital: "Pumpkin", category: "vegetable", emoji: "🎃" },
      { name: "National Song", capital: "Vande Mataram", category: "song", emoji: "🎶" },
      { name: "National Anthem", capital: "Jana Gana Mana", category: "anthem", emoji: "🎵" }
    ],
     families: [
       { name: "Lion", capital: "Cub", emoji: "🦁", image: "assets/animal-images/01_Lion_Cub.jpg" },
       { name: "Dog", capital: "Puppy", emoji: "🐶", image: "assets/animal-images/02_Dog_Puppy.jpg" },
       { name: "Cat", capital: "Kitten", emoji: "🐱", image: "assets/animal-images/03_Cat_Kitten.jpg" },
       { name: "Cow", capital: "Calf", emoji: "🐮", image: "assets/animal-images/04_Cow_Calf.jpg" },
       { name: "Horse", capital: "Foal", emoji: "🐴", image: "assets/animal-images/05_Horse_Foal.jpg" },
       { name: "Duck", capital: "Duckling", emoji: "🦆", image: "assets/animal-images/06_Duck_Duckling.jpg" },
       { name: "Sheep", capital: "Lamb", emoji: "🐑", image: "assets/animal-images/07_Sheep_Lamb.jpg" },
       { name: "Kangaroo", capital: "Joey", emoji: "🦘", image: "assets/animal-images/08_Kangaroo_Joey.jpg" },
       { name: "Pig", capital: "Piglet", emoji: "🐷", image: "assets/animal-images/09_Pig_Piglet.jpg" },
       { name: "Deer", capital: "Fawn", emoji: "🦌", image: "assets/animal-images/10_Deer_Fawn.jpg" },
       { name: "Goat", capital: "Kid", emoji: "🐐", image: "assets/animal-images/11_Goat_Kid.jpg" },
       { name: "Elephant", capital: "Calf", emoji: "🐘", image: "assets/animal-images/12_Elephant_Calf.jpg" },
       { name: "Frog", capital: "Tadpole", emoji: "🐸", image: "assets/animal-images/13_Frog_Tadpole.jpg" },
       { name: "Bear", capital: "Cub", emoji: "🐻", image: "assets/animal-images/14_Bear_Cub.jpg" },
       { name: "Hen", capital: "Chick", emoji: "🐔", image: "assets/animal-images/15_Hen_Chick.jpg" }
     ],
     homes: [
       { name: "Honeybee", capital: "Hive", emoji: "🐝", image: "assets/animal-homes/01_Honeybee_Hive.jpg" },
       { name: "Bird", capital: "Nest", emoji: "🐦", image: "assets/animal-homes/02_Bird_Nest.jpg" },
       { name: "Spider", capital: "Web", emoji: "🕷️", image: "assets/animal-homes/03_Spider_Web.jpg" },
       { name: "Lion", capital: "Den", emoji: "🦁", image: "assets/animal-homes/04_Lion_Den.jpg" },
       { name: "Rabbit", capital: "Burrow", emoji: "🐰", image: "assets/animal-homes/05_Rabbit_Burrow.jpg" },
       { name: "Ant", capital: "Anthill", emoji: "🐜", image: "assets/animal-homes/06_Ant_Anthill.jpg" },
       { name: "Dog", capital: "Kennel", emoji: "🐶", image: "assets/animal-homes/07_Dog_Kennel.jpg" },
       { name: "Horse", capital: "Stable", emoji: "🐴", image: "assets/animal-homes/08_Horse_Stable.jpg" },
       { name: "Fish", capital: "Ocean", emoji: "🐟", image: "assets/animal-homes/09_Fish_Ocean.jpg" },
       { name: "Owl", capital: "Hollow", emoji: "🦉", image: "assets/animal-homes/10_Owl_Hollow.jpg" },
       { name: "Bat", capital: "Cave", emoji: "🦇", image: "assets/animal-homes/11_Bat_Cave.jpg" },
       { name: "Pig", capital: "Sty", emoji: "🐷", image: "assets/animal-homes/12_Pig_Sty.jpg" },
       { name: "Hen", capital: "Coop", emoji: "🐔", image: "assets/animal-homes/13_Hen_Coop.jpg" },
       { name: "Polar Bear", capital: "Ice Cave", emoji: "🧊", image: "assets/animal-homes/14_PolarBear_IceCave.jpg" },
       { name: "Squirrel", capital: "Drey", emoji: "🐿️", image: "assets/animal-homes/15_Squirrel_Drey.jpg" }
     ],
      festivals: [
       { name: "Diwali", capital: "Diwali", hint: "The Festival of Lights", emoji: "🪔", image: "assets/festival-images/01_Diwali.jpg" },
       { name: "Holi", capital: "Holi", hint: "The Festival of Colors", emoji: "🌈", image: "assets/festival-images/02_Holi.jpg" },
       { name: "Ganesh Chaturthi", capital: "Ganesh Chaturthi", hint: "Lord Ganesha's Birthday", emoji: "🐘", image: "assets/festival-images/03_Ganesh_Chaturthi.jpg" },
       { name: "Navratri", capital: "Navratri", hint: "Nine nights of Dancing", emoji: "💃", image: "assets/festival-images/04_Navratri.jpg" },
       { name: "Dussehra", capital: "Dussehra", hint: "Victory of Good over Evil", emoji: "🏹", image: "assets/festival-images/05_Dussehra.jpg" },
       { name: "Raksha Bandhan", capital: "Raksha Bandhan", hint: "A bond between brother and sister", emoji: "🧶", image: "assets/festival-images/06_Raksha_Bandhan.jpg" },
       { name: "Krishna Janmashtami", capital: "Krishna Janmashtami", hint: "Lord Krishna's Birthday", emoji: "🍯", image: "assets/festival-images/07_Krishna_Janmashtami.jpg" },
       { name: "Eid-ul-Fitr", capital: "Eid-ul-Fitr", hint: "End of the holy month of Ramadan", emoji: "🌙", image: "assets/festival-images/08_Eid_ul_Fitr.jpg" },
       { name: "Christmas", capital: "Christmas", hint: "Jesus Christ's Birthday", emoji: "🎄", image: "assets/festival-images/09_Christmas.jpg" },
       { name: "Makar Sankranti", capital: "Makar Sankranti", hint: "Kite flying festival", emoji: "🪁", image: "assets/festival-images/10_Makar_Sankranti.jpg" },
       { name: "Pongal", capital: "Pongal", hint: "Harvest festival of Tamil Nadu", emoji: "🌾", image: "assets/festival-images/11_Pongal.jpg" },
       { name: "Onam", capital: "Onam", hint: "Harvest festival of Kerala", emoji: "🛶", image: "assets/festival-images/12_Onam.jpg" },
       { name: "Baisakhi", capital: "Baisakhi", hint: "Harvest festival of Punjab", emoji: "🚜", image: "assets/festival-images/13_Baisakhi.jpg" },
       { name: "Durga Puja", capital: "Durga Puja", hint: "Victory of Goddess Durga", emoji: "🔱", image: "assets/festival-images/14_Durga_Puja.jpg" },
       { name: "Gudhi Padwa", capital: "Gudhi Padwa", hint: "Marathi New Year", emoji: "🚩", image: "assets/festival-images/15_Gudhi_Padwa.jpg" },
       { name: "Bihu", capital: "Bihu", hint: "Harvest festival of Assam", emoji: "🎻", image: "assets/festival-images/16_Bihu.jpg" },
       { name: "Chhath Puja", capital: "Chhath Puja", hint: "Worship of the Sun God", emoji: "☀️", image: "assets/festival-images/17_Chhath_Puja.jpg" },
       { name: "Guru Nanak Jayanti", capital: "Guru Nanak Jayanti", hint: "Birthday of Guru Nanak Dev Ji", emoji: "🕯️", image: "assets/festival-images/18_Guru_Nanak_Jayanti.jpg" },
       { name: "Mahashivratri", capital: "Mahashivratri", hint: "The Great Night of Lord Shiva", emoji: "🔱", image: "assets/festival-images/19_Mahashivratri.jpg" },
       { name: "Basant Panchami", capital: "Basant Panchami", hint: "Worship of Goddess Saraswati", emoji: "🎻", image: "assets/festival-images/20_Basant_Panchami.jpg" },
       { name: "Karwa Chauth", capital: "Karwa Chauth", hint: "Wives fast for their husbands", emoji: "🥣", image: "assets/festival-images/21_Karwa_Chauth.jpg" },
       { name: "Ram Navami", capital: "Ram Navami", hint: "Lord Rama's Birthday", emoji: "🏹", image: "assets/festival-images/22_Ram_Navami.jpg" },
       { name: "Hanuman Jayanti", capital: "Hanuman Jayanti", hint: "Lord Hanuman's Birthday", emoji: "🐒", image: "assets/festival-images/23_Hanuman_Jayanti.jpg" },
       { name: "Lohri", capital: "Lohri", hint: "Punjabi winter bonfire festival", emoji: "🔥", image: "assets/festival-images/24_Lohri.jpg" },
       { name: "Buddha Purnima", capital: "Buddha Purnima", hint: "Lord Buddha's Birthday", emoji: "☸️", image: "assets/festival-images/25_Buddha_Purnima.jpg" },
       { name: "Mahavir Jayanti", capital: "Mahavir Jayanti", hint: "Lord Mahavir's Birthday", emoji: "🧘", image: "assets/festival-images/26_Mahavir_Jayanti.jpg" },
       { name: "Ugadi", capital: "Ugadi", hint: "New Year in Telugu and Kannada", emoji: "🥭", image: "assets/festival-images/27_Ugadi.jpg" },
       { name: "Vishu", capital: "Vishu", hint: "Malayalam New Year", emoji: "🌼", image: "assets/festival-images/28_Vishu.jpg" },
       { name: "Pana Sankranti", capital: "Pana Sankranti", hint: "Odia New Year", emoji: "🥤", image: "assets/festival-images/29_Pana_Sankranti.jpg" },
       { name: "Poila Baisakh", capital: "Poila Baisakh", hint: "Bengali New Year", emoji: "🥘", image: "assets/festival-images/30_Poila_Baisakh.jpg" },
       { name: "Hemis Festival", capital: "Hemis Festival", hint: "Mask dance festival of Ladakh", emoji: "👺", image: "assets/festival-images/31_Hemis_Festival.jpg" },
       { name: "Hornbill Festival", capital: "Hornbill Festival", hint: "Festival of Festivals in Nagaland", emoji: "🎺", image: "assets/festival-images/32_Hornbill_Festival.jpg" },
       { name: "Rath Yatra", capital: "Rath Yatra", hint: "The Chariot Festival", emoji: "🚜", image: "assets/festival-images/33_Rath_Yatra.jpg" },
       { name: "Kumbh Mela", capital: "Kumbh Mela", hint: "World's largest religious gathering", emoji: "🌊", image: "assets/festival-images/34_Kumbh_Mela.jpg" },
       { name: "Camel Festival", capital: "Camel Festival", hint: "Celebrated in Bikaner", emoji: "🐪", image: "assets/festival-images/35_Camel_Festival.jpg" },
       { name: "Pushkar Fair", capital: "Pushkar Fair", hint: "Famous livestock and camel fair", emoji: "🎡", image: "assets/festival-images/36_Pushkar_Fair.jpg" },
       { name: "Goa Carnival", capital: "Goa Carnival", hint: "Colorful parade and music", emoji: "🎭", image: "assets/festival-images/37_Goa_Carnival.jpg" },
       { name: "Thrissur Pooram", capital: "Thrissur Pooram", hint: "Grand elephant festival", emoji: "🐘", image: "assets/festival-images/38_Thrissur_Pooram.jpg" },
       { name: "Losar", capital: "Losar", hint: "Tibetan New Year", emoji: "🏔️", image: "assets/festival-images/39_Losar.jpg" },
       { name: "Bathukamma", capital: "Bathukamma", hint: "Flower festival of Telangana", emoji: "🌸", image: "assets/festival-images/40_Bathukamma.jpg" }
     ],
     body: [
        { name: "Which organ helps us breathe?", capital: "Lungs", emoji: "🫁", image: "assets/body-images/01_Lungs.jpg" },
        { name: "Which organ pumps blood to our body?", capital: "Heart", emoji: "❤️", image: "assets/body-images/02_Heart.jpg" },
        { name: "Which part helps us think and learn?", capital: "Brain", emoji: "🧠", image: "assets/body-images/03_Brain.jpg" },
        { name: "Which organ helps us digest food?", capital: "Stomach", emoji: "🥣", image: "assets/body-images/04_Stomach.jpg" },
        { name: "Which part of the body helps us see?", capital: "Eyes", emoji: "👀", image: "assets/body-images/05_Eyes.jpg" },
        { name: "Which part helps us hear music and sounds?", capital: "Ears", emoji: "👂", image: "assets/body-images/06_Ears.jpg" },
        { name: "Which part helps us smell flowers?", capital: "Nose", emoji: "👃", image: "assets/body-images/07_Nose.jpg" },
        { name: "Which part helps us taste yummy food?", capital: "Tongue", emoji: "👅", image: "assets/body-images/08_Tongue.jpg" },
        { name: "What covers our whole body and protects it?", capital: "Skin", emoji: "🤚", image: "assets/body-images/09_Skin.jpg" },
        { name: "What are the hard parts that make our frame?", capital: "Bones", emoji: "🦴", image: "assets/body-images/10_Bones.jpg" },
        { name: "Which part helps us chew our food?", capital: "Teeth", emoji: "🦷", image: "assets/body-images/11_Teeth.jpg" },
        { name: "Which part helps us hold and grab things?", capital: "Hands", emoji: "🖐️", image: "assets/body-images/12_Hands.jpg" },
        { name: "Which part helps us walk and run?", capital: "Legs", emoji: "🦵", image: "assets/body-images/13_Legs.jpg" },
        { name: "Which part helps our arms bend?", capital: "Elbow", emoji: "💪", image: "assets/body-images/14_Elbow.jpg" },
        { name: "Which part helps our legs bend?", capital: "Knee", emoji: "🦵", image: "assets/body-images/15_Knee.jpg" }
      ],
      helpers: [
        {"name": "Stethoscope", "capital": "Doctor", "emoji": "🩺", "image": "assets/helper-images/01_Stethoscope.jpg"},
        {"name": "Fire Truck", "capital": "Firefighter", "emoji": "🚒", "image": "assets/helper-images/02_Fire_Truck.jpg"},
        {"name": "Police Car", "capital": "Police Officer", "emoji": "🚓", "image": "assets/helper-images/03_Police_Car.jpg"},
        {"name": "Chalkboard", "capital": "Teacher", "emoji": "🧑‍🏫", "image": "assets/helper-images/04_Chalkboard.jpg"},
        {"name": "Baking Oven", "capital": "Baker", "emoji": "🥯", "image": "assets/helper-images/05_Baking_Oven.jpg"},
        {"name": "Airplane", "capital": "Pilot", "emoji": "✈️", "image": "assets/helper-images/06_Airplane.jpg"},
        {"name": "Mail Bag", "capital": "Postman", "emoji": "📬", "image": "assets/helper-images/07_Mail_Bag.jpg"},
        {"name": "Paint Palette", "capital": "Artist", "emoji": "🎨", "image": "assets/helper-images/08_Paint_Palette.jpg"},
        {"name": "Microscope", "capital": "Scientist", "emoji": "🔬", "image": "assets/helper-images/09_Microscope.jpg"},
        {"name": "Wrench", "capital": "Mechanic", "emoji": "🔧", "image": "assets/helper-images/10_Wrench.jpg"},
        {"name": "Spaceship", "capital": "Astronaut", "emoji": "🚀", "image": "assets/helper-images/11_Spaceship.jpg"},
        {"name": "Frying Pan", "capital": "Chef", "emoji": "🍳", "image": "assets/helper-images/12_Frying_Pan.jpg"},
        {"name": "Gardening Hoe", "capital": "Gardener", "emoji": "🪴", "image": "assets/helper-images/13_Gardening_Hoe.jpg"},
        {"name": "Library Books", "capital": "Librarian", "emoji": "📚", "image": "assets/helper-images/14_Library_Books.jpg"},
        {"name": "Bus", "capital": "Bus Driver", "emoji": "🚌", "image": "assets/helper-images/15_Bus.jpg"},
        {"name": "Tractor", "capital": "Farmer", "emoji": "🚜", "image": "assets/helper-images/16_Tractor.jpg"},
        {"name": "Thermometer", "capital": "Nurse", "emoji": "🌡️", "image": "assets/helper-images/17_Thermometer.jpg"},
        {"name": "Hammer", "capital": "Carpenter", "emoji": "🔨", "image": "assets/helper-images/18_Hammer.jpg"},
        {"name": "Whistle", "capital": "Coach", "emoji": "📢", "image": "assets/helper-images/19_Whistle.jpg"},
        {"name": "Microphone", "capital": "Singer", "emoji": "🎤", "image": "assets/helper-images/20_Microphone.jpg"},
        {"name": "Camera", "capital": "Photographer", "emoji": "📷", "image": "assets/helper-images/21_Camera.jpg"},
        {"name": "Computer", "capital": "Programmer", "emoji": "💻", "image": "assets/helper-images/22_Computer.jpg"},
        {"name": "Sewing Machine", "capital": "Tailor", "emoji": "🧵", "image": "assets/helper-images/23_Sewing_Machine.jpg"},
        {"name": "Trash Truck", "capital": "Sanitation Worker", "emoji": "🚛", "image": "assets/helper-images/24_Trash_Truck.jpg"},
        {"name": "Dental Mirror", "capital": "Dentist", "emoji": "🦷", "image": "assets/helper-images/25_Dental_Mirror.jpg"}
      ],
materials: [
         {"name": "Key", "capital": "Metal", "emoji": "🔑", "image": "assets/material-images/01_Key.jpg"},
         {"name": "Water Bottle", "capital": "Plastic", "emoji": "🧴", "image": "assets/material-images/02_Water_Bottle.jpg"},
         {"name": "Window", "capital": "Glass", "emoji": "🪟", "image": "assets/material-images/03_Window.jpg"},
         {"name": "Table", "capital": "Wood", "emoji": "🪑", "image": "assets/material-images/04_Table.jpg"},
         {"name": "Teddy Bear", "capital": "Fabric", "emoji": "🧸", "image": "assets/material-images/05_Teddy_Bear.jpg"},
         {"name": "Spoon", "capital": "Metal", "emoji": "🥄", "image": "assets/material-images/06_Spoon.jpg"},
         {"name": "Pencil", "capital": "Wood", "emoji": "✏️", "image": "assets/material-images/07_Pencil.jpg"},
         {"name": "Drinking Glass", "capital": "Glass", "emoji": "🥛", "image": "assets/material-images/08_Drinking_Glass.jpg"},
         {"name": "T-shirt", "capital": "Fabric", "emoji": "👕", "image": "assets/material-images/09_Tshirt.jpg"},
         {"name": "Toy Car", "capital": "Plastic", "emoji": "🏎️", "image": "assets/material-images/10_Toy_Car.jpg"},
         {"name": "Hammer", "capital": "Metal", "emoji": "🔨", "image": "assets/material-images/11_Hammer.jpg"},
         {"name": "Door", "capital": "Wood", "emoji": "🚪", "image": "assets/material-images/12_Door.jpg"},
         {"name": "Eyeglasses", "capital": "Glass", "emoji": "👓", "image": "assets/material-images/13_Eyeglasses.jpg"},
         {"name": "Pillow", "capital": "Fabric", "emoji": "🛌", "image": "assets/material-images/14_Pillow.jpg"},
         {"name": "Lunch Box", "capital": "Plastic", "emoji": "🍱", "image": "assets/material-images/15_Lunch_Box.jpg"},
         {"name": "Coin", "capital": "Metal", "emoji": "🪙", "image": "assets/material-images/16_Coin.jpg"},
         {"name": "Bat", "capital": "Wood", "emoji": "🏏", "image": "assets/material-images/17_Bat.jpg"},
         {"name": "Mirror", "capital": "Glass", "emoji": "🪞", "image": "assets/material-images/18_Mirror.jpg"},
         {"name": "Curtains", "capital": "Fabric", "emoji": "カーテン", "image": "assets/material-images/19_Curtains.jpg"},
         {"name": "Straw", "capital": "Plastic", "emoji": "🥤", "image": "assets/material-images/20_Straw.jpg"},
         {"name": "Bicycle", "capital": "Metal", "emoji": "🚲", "image": "assets/material-images/21_Bicycle.jpg"},
         {"name": "Fence", "capital": "Wood", "emoji": "🪵", "image": "assets/material-images/22_Fence.jpg"},
         {"name": "Lightbulb", "capital": "Glass", "emoji": "💡", "image": "assets/material-images/23_Lightbulb.jpg"},
         {"name": "Socks", "capital": "Fabric", "emoji": "🧦", "image": "assets/material-images/24_Socks.jpg"},
         {"name": "Bucket", "capital": "Plastic", "emoji": "🪣", "image": "assets/material-images/25_Bucket.jpg"}
       ],

      countries: [
        { "name": "Afghanistan", "capital": "Kabul", "phonetic": "Afghanistan" },
        { "name": "Albania", "capital": "Tirana", "phonetic": "Albania" },
        { "name": "Algeria", "capital": "Algiers", "phonetic": "Algeria" },
        { "name": "Andorra", "capital": "Andorra la Vella", "phonetic": "Andorra" },
        { "name": "Angola", "capital": "Luanda", "phonetic": "Angola" },
        { "name": "Antigua and Barbuda", "capital": "Saint John's", "phonetic": "Antigua and Barbuda" },
        { "name": "Argentina", "capital": "Buenos Aires", "phonetic": "Argentina" },
        { "name": "Armenia", "capital": "Yerevan", "phonetic": "Armenia" },
        { "name": "Australia", "capital": "Canberra", "phonetic": "Australia" },
        { "name": "Austria", "capital": "Vienna", "phonetic": "Austria" },
        { "name": "Azerbaijan", "capital": "Baku", "phonetic": "Azerbaijan" },
        { "name": "Bahamas", "capital": "Nassau", "phonetic": "Bahamas" },
        { "name": "Bahrain", "capital": "Manama", "phonetic": "Bahrain" },
        { "name": "Bangladesh", "capital": "Dhaka", "phonetic": "Bangladesh" },
        { "name": "Barbados", "capital": "Bridgetown", "phonetic": "Barbados" },
        { "name": "Belarus", "capital": "Minsk", "phonetic": "Belarus" },
        { "name": "Belgium", "capital": "Brussels", "phonetic": "Belgium" },
        { "name": "Belize", "capital": "Belmopan", "phonetic": "Belize" },
        { "name": "Benin", "capital": "Porto-Novo", "phonetic": "Benin" },
        { "name": "Bhutan", "capital": "Thimphu", "phonetic": "Bhutan" },
        { "name": "Bolivia", "capital": "Sucre", "phonetic": "Bolivia" },
        { "name": "Bosnia and Herzegovina", "capital": "Sarajevo", "phonetic": "Bosnia and Herzegovina" },
        { "name": "Botswana", "capital": "Gaborone", "phonetic": "Botswana" },
        { "name": "Brazil", "capital": "Brasilia", "phonetic": "Brazil" },
        { "name": "Brunei", "capital": "Bandar Seri Begawan", "phonetic": "Brunei" },
        { "name": "Bulgaria", "capital": "Sofia", "phonetic": "Bulgaria" },
        { "name": "Burkina Faso", "capital": "Ouagadougou", "phonetic": "Burkina Faso" },
        { "name": "Burundi", "capital": "Gitega", "phonetic": "Burundi" },
        { "name": "Cabo Verde", "capital": "Praia", "phonetic": "Cabo Verde" },
        { "name": "Cambodia", "capital": "Phnom Penh", "phonetic": "Cambodia" },
        { "name": "Cameroon", "capital": "Yaounde", "phonetic": "Cameroon" },
        { "name": "Canada", "capital": "Ottawa", "phonetic": "Canada" },
        { "name": "Central African Republic", "capital": "Bangui", "phonetic": "Central African Republic" },
        { "name": "Chad", "capital": "N'Djamena", "phonetic": "Chad" },
        { "name": "Chile", "capital": "Santiago", "phonetic": "Chile" },
        { "name": "China", "capital": "Beijing", "phonetic": "China" },
        { "name": "Colombia", "capital": "Bogota", "phonetic": "Colombia" },
        { "name": "Comoros", "capital": "Moroni", "phonetic": "Comoros" },
        { "name": "Congo (Congo-Brazzaville)", "capital": "Brazzaville", "phonetic": "Congo" },
        { "name": "Costa Rica", "capital": "San Jose", "phonetic": "Costa Rica" },
        { "name": "Croatia", "capital": "Zagreb", "phonetic": "Croatia" },
        { "name": "Cuba", "capital": "Havana", "phonetic": "Cuba" },
        { "name": "Cyprus", "capital": "Nicosia", "phonetic": "Cyprus" },
        { "name": "Czechia (Czech Republic)", "capital": "Prague", "phonetic": "Czechia" },
        { "name": "Democratic Republic of the Congo", "capital": "Kinshasa", "phonetic": "Democratic Republic of the Congo" },
        { "name": "Denmark", "capital": "Copenhagen", "phonetic": "Denmark" },
        { "name": "Djibouti", "capital": "Djibouti", "phonetic": "Djibouti" },
        { "name": "Dominica", "capital": "Roseau", "phonetic": "Dominica" },
        { "name": "Dominican Republic", "capital": "Santo Domingo", "phonetic": "Dominican Republic" },
        { "name": "Ecuador", "capital": "Quito", "phonetic": "Ecuador" },
        { "name": "Egypt", "capital": "Cairo", "phonetic": "Egypt" },
        { "name": "El Salvador", "capital": "San Salvador", "phonetic": "El Salvador" },
        { "name": "Equatorial Guinea", "capital": "Malabo", "phonetic": "Equatorial Guinea" },
        { "name": "Eritrea", "capital": "Asmara", "phonetic": "Eritrea" },
        { "name": "Estonia", "capital": "Tallinn", "phonetic": "Estonia" },
        { "name": "Eswatini", "capital": "Mbabane", "phonetic": "Eswatini" },
        { "name": "Ethiopia", "capital": "Addis Ababa", "phonetic": "Ethiopia" },
        { "name": "Fiji", "capital": "Suva", "phonetic": "Fiji" },
        { "name": "Finland", "capital": "Helsinki", "phonetic": "Finland" },
        { "name": "France", "capital": "Paris", "phonetic": "France" },
        { "name": "Gabon", "capital": "Libreville", "phonetic": "Gabon" },
        { "name": "Gambia", "capital": "Banjul", "phonetic": "Gambia" },
        { "name": "Georgia", "capital": "Tbilisi", "phonetic": "Georgia" },
        { "name": "Germany", "capital": "Berlin", "phonetic": "Germany" },
        { "name": "Ghana", "capital": "Accra", "phonetic": "Ghana" },
        { "name": "Greece", "capital": "Athens", "phonetic": "Greece" },
        { "name": "Grenada", "capital": "Saint George's", "phonetic": "Grenada" },
        { "name": "Guatemala", "capital": "Guatemala City", "phonetic": "Guatemala" },
        { "name": "Guinea", "capital": "Conakry", "phonetic": "Guinea" },
        { "name": "Guinea-Bissau", "capital": "Bissau", "phonetic": "Guinea Bissau" },
        { "name": "Guyana", "capital": "Georgetown", "phonetic": "Guyana" },
        { "name": "Haiti", "capital": "Port-au-Prince", "phonetic": "Haiti" },
        { "name": "Honduras", "capital": "Tegucigalpa", "phonetic": "Honduras" },
        { "name": "Hungary", "capital": "Budapest", "phonetic": "Hungary" },
        { "name": "Iceland", "capital": "Reykjavik", "phonetic": "Iceland" },
        { "name": "India", "capital": "New Delhi", "phonetic": "India" },
        { "name": "Indonesia", "capital": "Jakarta", "phonetic": "Indonesia" },
        { "name": "Iran", "capital": "Tehran", "phonetic": "Iran" },
        { "name": "Iraq", "capital": "Baghdad", "phonetic": "Iraq" },
        { "name": "Ireland", "capital": "Dublin", "phonetic": "Ireland" },
        { "name": "Israel", "capital": "Jerusalem", "phonetic": "Israel" },
        { "name": "Italy", "capital": "Rome", "phonetic": "Italy" },
        { "name": "Ivory Coast", "capital": "Yamoussoukro", "phonetic": "Ivory Coast" },
        { "name": "Jamaica", "capital": "Kingston", "phonetic": "Jamaica" },
        { "name": "Japan", "capital": "Tokyo", "phonetic": "Japan" },
        { "name": "Jordan", "capital": "Amman", "phonetic": "Jordan" },
        { "name": "Kazakhstan", "capital": "Astana", "phonetic": "Kazakhstan" },
        { "name": "Kenya", "capital": "Nairobi", "phonetic": "Kenya" },
        { "name": "Kiribati", "capital": "Tarawa", "phonetic": "Kiribati" },
        { "name": "Kuwait", "capital": "Kuwait City", "phonetic": "Kuwait" },
        { "name": "Kyrgyzstan", "capital": "Bishkek", "phonetic": "Kyrgyzstan" },
        { "name": "Laos", "capital": "Vientiane", "phonetic": "Laos" },
        { "name": "Latvia", "capital": "Riga", "phonetic": "Latvia" },
        { "name": "Lebanon", "capital": "Beirut", "phonetic": "Lebanon" },
        { "name": "Lesotho", "capital": "Maseru", "phonetic": "Lesotho" },
        { "name": "Liberia", "capital": "Monrovia", "phonetic": "Liberia" },
        { "name": "Libya", "capital": "Tripoli", "phonetic": "Libya" },
        { "name": "Liechtenstein", "capital": "Vaduz", "phonetic": "Liechtenstein" },
        { "name": "Lithuania", "capital": "Vilnius", "phonetic": "Lithuania" },
        { "name": "Luxembourg", "capital": "Luxembourg", "phonetic": "Luxembourg" },
        { "name": "Madagascar", "capital": "Antananarivo", "phonetic": "Madagascar" },
        { "name": "Malawi", "capital": "Lilongwe", "phonetic": "Malawi" },
        { "name": "Malaysia", "capital": "Kuala Lumpur", "phonetic": "Malaysia" },
        { "name": "Maldives", "capital": "Male", "phonetic": "Maldives" },
        { "name": "Mali", "capital": "Bamako", "phonetic": "Mali" },
        { "name": "Malta", "capital": "Valletta", "phonetic": "Malta" },
        { "name": "Marshall Islands", "capital": "Majuro", "phonetic": "Marshall Islands" },
        { "name": "Mauritania", "capital": "Nouakchott", "phonetic": "Mauritania" },
        { "name": "Mauritius", "capital": "Port Louis", "phonetic": "Mauritius" },
        { "name": "Mexico", "capital": "Mexico City", "phonetic": "Mexico" },
        { "name": "Micronesia", "capital": "Palikir", "phonetic": "Micronesia" },
        { "name": "Moldova", "capital": "Chisinau", "phonetic": "Moldova" },
        { "name": "Monaco", "capital": "Monaco", "phonetic": "Monaco" },
        { "name": "Mongolia", "capital": "Ulaanbaatar", "phonetic": "Mongolia" },
        { "name": "Montenegro", "capital": "Podgorica", "phonetic": "Montenegro" },
        { "name": "Morocco", "capital": "Rabat", "phonetic": "Morocco" },
        { "name": "Mozambique", "capital": "Maputo", "phonetic": "Mozambique" },
        { "name": "Myanmar (Burma)", "capital": "Naypyidaw", "phonetic": "Myanmar" },
        { "name": "Namibia", "capital": "Windhoek", "phonetic": "Namibia" },
        { "name": "Nauru", "capital": "Yaren", "phonetic": "Nauru" },
        { "name": "Nepal", "capital": "Kathmandu", "phonetic": "Nepal" },
        { "name": "Netherlands", "capital": "Amsterdam", "phonetic": "Netherlands" },
        { "name": "New Zealand", "capital": "Wellington", "phonetic": "New Zealand" },
        { "name": "Nicaragua", "capital": "Managua", "phonetic": "Nicaragua" },
        { "name": "Niger", "capital": "Niamey", "phonetic": "Niger" },
        { "name": "Nigeria", "capital": "Abuja", "phonetic": "Nigeria" },
        { "name": "North Korea", "capital": "Pyongyang", "phonetic": "North Korea" },
        { "name": "North Macedonia", "capital": "Skopje", "phonetic": "North Macedonia" },
        { "name": "Norway", "capital": "Oslo", "phonetic": "Norway" },
        { "name": "Oman", "capital": "Muscat", "phonetic": "Oman" },
        { "name": "Pakistan", "capital": "Islamabad", "phonetic": "Pakistan" },
        { "name": "Palau", "capital": "Ngerulmud", "phonetic": "Palau" },
        { "name": "Palestine", "capital": "Jerusalem", "phonetic": "Palestine" },
        { "name": "Panama", "capital": "Panama City", "phonetic": "Panama" },
        { "name": "Papua New Guinea", "capital": "Port Moresby", "phonetic": "Papua New Guinea" },
        { "name": "Paraguay", "capital": "Asuncion", "phonetic": "Paraguay" },
        { "name": "Peru", "capital": "Lima", "phonetic": "Peru" },
        { "name": "Philippines", "capital": "Manila", "phonetic": "Philippines" },
        { "name": "Poland", "capital": "Warsaw", "phonetic": "Poland" },
        { "name": "Portugal", "capital": "Lisbon", "phonetic": "Portugal" },
        { "name": "Qatar", "capital": "Doha", "phonetic": "Qatar" },
        { "name": "Romania", "capital": "Bucharest", "phonetic": "Romania" },
        { "name": "Russia", "capital": "Moscow", "phonetic": "Russia" },
        { "name": "Rwanda", "capital": "Kigali", "phonetic": "Rwanda" },
        { "name": "Saint Kitts and Nevis", "capital": "Basseterre", "phonetic": "Saint Kitts and Nevis" },
        { "name": "Saint Lucia", "capital": "Castries", "phonetic": "Saint Lucia" },
        { "name": "Saint Vincent and the Grenadines", "capital": "Kingstown", "phonetic": "Saint Vincent and the Grenadines" },
        { "name": "Samoa", "capital": "Apia", "phonetic": "Samoa" },
        { "name": "San Marino", "capital": "San Marino", "phonetic": "San Marino" },
        { "name": "Sao Tome and Principe", "capital": "Sao Tome", "phonetic": "Sao Tome and Principe" },
        { "name": "Saudi Arabia", "capital": "Riyadh", "phonetic": "Saudi Arabia" },
        { "name": "Senegal", "capital": "Dakar", "phonetic": "Senegal" },
        { "name": "Serbia", "capital": "Belgrade", "phonetic": "Serbia" },
        { "name": "Seychelles", "capital": "Victoria", "phonetic": "Seychelles" },
        { "name": "Sierra Leone", "capital": "Freetown", "phonetic": "Sierra Leone" },
        { "name": "Singapore", "capital": "Singapore", "phonetic": "Singapore" },
        { "name": "Slovakia", "capital": "Bratislava", "phonetic": "Slovakia" },
        { "name": "Slovenia", "capital": "Ljubljana", "phonetic": "Slovenia" },
        { "name": "Solomon Islands", "capital": "Honiara", "phonetic": "Solomon Islands" },
        { "name": "Somalia", "capital": "Mogadishu", "phonetic": "Somalia" },
        { "name": "South Africa", "capital": "Pretoria", "phonetic": "South Africa" },
        { "name": "South Korea", "capital": "Seoul", "phonetic": "South Korea" },
        { "name": "South Sudan", "capital": "Juba", "phonetic": "South Sudan" },
        { "name": "Spain", "capital": "Madrid", "phonetic": "Spain" },
        { "name": "Sri Lanka", "capital": "Sri Jayawardenepura Kotte", "phonetic": "Sri Lanka" },
        { "name": "Sudan", "capital": "Khartoum", "phonetic": "Sudan" },
        { "name": "Suriname", "capital": "Paramaribo", "phonetic": "Suriname" },
        { "name": "Sweden", "capital": "Stockholm", "phonetic": "Sweden" },
        { "name": "Switzerland", "capital": "Bern", "phonetic": "Switzerland" },
        { "name": "Syria", "capital": "Damascus", "phonetic": "Syria" },
        { "name": "Taiwan", "capital": "Taipei", "phonetic": "Taiwan" },
        { "name": "Tajikistan", "capital": "Dushanbe", "phonetic": "Tajikistan" },
        { "name": "Tanzania", "capital": "Dodoma", "phonetic": "Tanzania" },
        { "name": "Thailand", "capital": "Bangkok", "phonetic": "Thailand" },
        { "name": "Timor-Leste", "capital": "Dili", "phonetic": "Timor Leste" },
        { "name": "Togo", "capital": "Lome", "phonetic": "Togo" },
        { "name": "Tonga", "capital": "Nuku'alofa", "phonetic": "Tonga" },
        { "name": "Trinidad and Tobago", "capital": "Port of Spain", "phonetic": "Trinidad and Tobago" },
        { "name": "Tunisia", "capital": "Tunis", "phonetic": "Tunisia" },
        { "name": "Turkey", "capital": "Ankara", "phonetic": "Turkey" },
        { "name": "Turkmenistan", "capital": "Ashgabat", "phonetic": "Turkmenistan" },
        { "name": "Tuvalu", "capital": "Funafuti", "phonetic": "Tuvalu" },
        { "name": "Uganda", "capital": "Kampala", "phonetic": "Uganda" },
        { "name": "Ukraine", "capital": "Kyiv", "phonetic": "Ukraine" },
        { "name": "United Arab Emirates", "capital": "Abu Dhabi", "phonetic": "United Arab Emirates" },
        { "name": "United Kingdom", "capital": "London", "phonetic": "United Kingdom" },
        { "name": "United States of America", "capital": "Washington, D.C.", "phonetic": "United States of America" },
        { "name": "Uruguay", "capital": "Montevideo", "phonetic": "Uruguay" },
        { "name": "Uzbekistan", "capital": "Tashkent", "phonetic": "Uzbekistan" },
        { "name": "Vanuatu", "capital": "Port Vila", "phonetic": "Vanuatu" },
        { "name": "Vatican City", "capital": "Vatican City", "phonetic": "Vatican City" },
        { "name": "Venezuela", "capital": "Caracas", "phonetic": "Venezuela" },
        { "name": "Vietnam", "capital": "Hanoi", "phonetic": "Vietnam" },
        { "name": "Yemen", "capital": "Sana'a", "phonetic": "Yemen" },
        { "name": "Zambia", "capital": "Lusaka", "phonetic": "Zambia" },
{ "name": "Zimbabwe", "capital": "Harare", "phonetic": "Zimbabwe" }
      ],

      "habits": [
    { "name": "Washing hands with soap before eating meals", "capital": "Good Habit", "phonetic": "Washing hands with soap before eating meals", "image": "assets/habits-images/001_washing_hands_with_soap_before_eating_meals.png" },
    { "name": "Leaving toys scattered all over the living room floor", "capital": "Bad Habit", "phonetic": "Leaving toys scattered all over the living room floor", "image": "assets/habits-images/002_leaving_toys_scattered_all_over_the_living_room_floor.png" },
    { "name": "Brushing your teeth at least twice a day", "capital": "Good Habit", "phonetic": "Brushing your teeth at least twice a day", "image": "assets/habits-images/003_brushing_your_teeth_at_least_twice_a_day.png" },
    { "name": "Coughing or sneezing into your elbow or a tissue", "capital": "Good Habit", "phonetic": "Coughing or sneezing into your elbow or a tissue", "image": "assets/habits-images/004_coughing_or_sneezing_into_your_elbow_or_a_tissue.png" },
    { "name": "Staying up very late playing video games on a school night", "capital": "Bad Habit", "phonetic": "Staying up very late playing video games on a school night", "image": "assets/habits-images/005_staying_up_very_late_playing_video_games_on_a_school_night.png" },
    { "name": "Drinking water throughout the day to stay hydrated", "capital": "Good Habit", "phonetic": "Drinking water throughout the day to stay hydrated", "image": "assets/habits-images/006_drinking_water_throughout_the_day_to_stay_hydrated.png" },
    { "name": "Interrupting someone while they are speaking to you", "capital": "Bad Habit", "phonetic": "Interrupting someone while they are speaking to you", "image": "assets/habits-images/007_interrupting_someone_while_they_are_speaking_to_you.png" },
    { "name": "Making your bed every morning after waking up", "capital": "Good Habit", "phonetic": "Making your bed every morning after waking up", "image": "assets/habits-images/008_making_your_bed_every_morning_after_waking_up.png" },
    { "name": "Taking slow, deep breaths when you feel angry", "capital": "Good Habit", "phonetic": "Taking slow, deep breaths when you feel angry", "image": "assets/habits-images/009_taking_slow_deep_breaths_when_you_feel_angry.png" },
    { "name": "Skipping breakfast on a regular basis", "capital": "Bad Habit", "phonetic": "Skipping breakfast on a regular basis", "image": "assets/habits-images/010_skipping_breakfast_on_a_regular_basis.png" },
    { "name": "Throwing trash into a bin or recycling can", "capital": "Good Habit", "phonetic": "Throwing trash into a bin or recycling can", "image": "assets/habits-images/011_throwing_trash_into_a_bin_or_recycling_can.png" },
    { "name": "Slouching for hours while looking at a phone screen", "capital": "Bad Habit", "phonetic": "Slouching for hours while looking at a phone screen", "image": "assets/habits-images/012_slouching_for_hours_while_looking_at_a_phone_screen.png" },
    { "name": "Saying 'Please' and 'Thank you' to express gratitude", "capital": "Good Habit", "phonetic": "Saying 'Please' and 'Thank you' to express gratitude", "image": "assets/habits-images/013_saying_please_and_thank_you_to_express_gratitude.png" },
    { "name": "Reading books regularly to sharpen your mind", "capital": "Good Habit", "phonetic": "Reading books regularly to sharpen your mind", "image": "assets/habits-images/014_reading_books_regularly_to_sharpen_your_mind.png" },
    { "name": "Biting or chewing on pencils and pens at school", "capital": "Bad Habit", "phonetic": "Biting or chewing on pencils and pens at school", "image": "assets/habits-images/015_biting_or_chewing_on_pencils_and_pens_at_school.png" },
    { "name": "Packing your school bag the night before", "capital": "Good Habit", "phonetic": "Packing your school bag the night before", "image": "assets/habits-images/016_packing_your_school_bag_the_night_before.png" },
    { "name": "Washing your face when you wake up to feel refreshed", "capital": "Good Habit", "phonetic": "Washing your face when you wake up to feel refreshed", "image": "assets/habits-images/017_washing_your_face_when_you_wake_up_to_feel_refreshed.png" },
    { "name": "Biting your fingernails when you feel worried", "capital": "Bad Habit", "phonetic": "Biting your fingernails when you feel worried", "image": "assets/habits-images/018_biting_your_fingernails_when_you_feel_worried.png" },
    { "name": "Eating a variety of fruits and vegetables every day", "capital": "Good Habit", "phonetic": "Eating a variety of fruits and vegetables every day", "image": "assets/habits-images/019_eating_a_variety_of_fruits_and_vegetables_every_day.png" },
    { "name": "Leaving the water running while brushing your teeth", "capital": "Bad Habit", "phonetic": "Leaving the water running while brushing your teeth", "image": "assets/habits-images/020_leaving_the_water_running_while_brushing_your_teeth.png" },
    { "name": "Going to bed at a consistent time every night", "capital": "Good Habit", "phonetic": "Going to bed at a consistent time every night", "image": "assets/habits-images/021_going_to_bed_at_a_consistent_time_every_night.png" },
    { "name": "Wiping muddy shoes on the mat before entering the house", "capital": "Good Habit", "phonetic": "Wiping muddy shoes on the mat before entering the house", "image": "assets/habits-images/022_wiping_muddy_shoes_on_the_mat_before_entering_the_house.png" },
    { "name": "Telling the truth immediately when you break something", "capital": "Good Habit", "phonetic": "Telling the truth immediately when you break something", "image": "assets/habits-images/023_telling_the_truth_immediately_when_you_break_something.png" },
    { "name": "Washing your hands thoroughly after using the restroom", "capital": "Good Habit", "phonetic": "Washing your hands thoroughly after using the restroom", "image": "assets/habits-images/024_washing_your_hands_thoroughly_after_using_the_restroom.png" },
    { "name": "Eating snacks directly out of a giant family-sized bag", "capital": "Bad Habit", "phonetic": "Eating snacks directly out of a giant family-sized bag", "image": "assets/habits-images/025_eating_snacks_directly_out_of_a_giant_family-sized_bag.png" },
    { "name": "Exercising daily or playing active games outdoors", "capital": "Good Habit", "phonetic": "Exercising daily or playing active games outdoors", "image": "assets/habits-images/026_exercising_daily_or_playing_active_games_outdoors.png" },
    { "name": "Slamming doors loudly when walking through them", "capital": "Bad Habit", "phonetic": "Slamming doors loudly when walking through them", "image": "assets/habits-images/027_slamming_doors_loudly_when_walking_through_them.png" },
    { "name": "Looking left, right, and left again before crossing a street", "capital": "Good Habit", "phonetic": "Looking left, right, and left again before crossing a street", "image": "assets/habits-images/028_looking_left_right_and_left_again_before_crossing_a_street.png" },
    { "name": "Flossing between your teeth daily to remove hidden plaque", "capital": "Good Habit", "phonetic": "Flossing between your teeth daily to remove hidden plaque", "image": "assets/habits-images/029_flossing_between_your_teeth_daily_to_remove_hidden_plaque.png" },
    { "name": "Making fun of a classmate because they made a mistake", "capital": "Bad Habit", "phonetic": "Making fun of a classmate because they made a mistake", "image": "assets/habits-images/030_making_fun_of_a_classmate_because_they_made_a_mistake.png" },
    { "name": "Saving a portion of your allowance inside a piggy bank", "capital": "Good Habit", "phonetic": "Saving a portion of your allowance inside a piggy bank", "image": "assets/habits-images/031_saving_a_portion_of_your_allowance_inside_a_piggy_bank.png" },
    { "name": "Chewing your food with your mouth wide open", "capital": "Bad Habit", "phonetic": "Chewing your food with your mouth wide open", "image": "assets/habits-images/032_chewing_your_food_with_your_mouth_wide_open.png" },
    { "name": "Taking good care of borrowed toys and returning them promptly", "capital": "Good Habit", "phonetic": "Taking good care of borrowed toys and returning them promptly", "image": "assets/habits-images/033_taking_good_care_of_borrowed_toys_and_returning_them_promptl.png" },
    { "name": "Taking a bath or shower regularly to stay clean", "capital": "Good Habit", "phonetic": "Taking a bath or shower regularly to stay clean", "image": "assets/habits-images/034_taking_a_bath_or_shower_regularly_to_stay_clean.png" },
    { "name": "Checking both ways for traffic when stepping off a school bus", "capital": "Good Habit", "phonetic": "Checking both ways for traffic when stepping off a school bus", "image": "assets/habits-images/035_checking_both_ways_for_traffic_when_stepping_off_a_school_bu.png" },
    { "name": "Putting off homework assignments until the very last minute", "capital": "Bad Habit", "phonetic": "Putting off homework assignments until the very last minute", "image": "assets/habits-images/036_putting_off_homework_assignments_until_the_very_last_minute.png" },
    { "name": "Hanging up your coat and putting shoes away when arriving home", "capital": "Good Habit", "phonetic": "Hanging up your coat and putting shoes away when arriving home", "image": "assets/habits-images/037_hanging_up_your_coat_and_putting_shoes_away_when_arriving_ho.png" },
    { "name": "Spending active time outside in nature to breathe fresh air", "capital": "Good Habit", "phonetic": "Spending active time outside in nature to breathe fresh air", "image": "assets/habits-images/038_spending_active_time_outside_in_nature_to_breathe_fresh_air.png" },
    { "name": "Whispering or talking quietly inside a public library", "capital": "Good Habit", "phonetic": "Whispering or talking quietly inside a public library", "image": "assets/habits-images/039_whispering_or_talking_quietly_inside_a_public_library.png" },
    { "name": "Talking with a mouth completely full of food", "capital": "Bad Habit", "phonetic": "Talking with a mouth completely full of food", "image": "assets/habits-images/040_talking_with_a_mouth_completely_full_of_food.png" },
    { "name": "Holding the door open for someone walking right behind you", "capital": "Good Habit", "phonetic": "Holding the door open for someone walking right behind you", "image": "assets/habits-images/041_holding_the_door_open_for_someone_walking_right_behind_you.png" },
    { "name": "Washing reusable water bottles daily with soap", "capital": "Good Habit", "phonetic": "Washing reusable water bottles daily with soap", "image": "assets/habits-images/042_washing_reusable_water_bottles_daily_with_soap.png" },
    { "name": "Rolling your eyes when an adult asks you to do a chore", "capital": "Bad Habit", "phonetic": "Rolling your eyes when an adult asks you to do a chore", "image": "assets/habits-images/043_rolling_your_eyes_when_an_adult_asks_you_to_do_a_chore.png" },
    { "name": "Setting up a specific, quiet study spot for schoolwork", "capital": "Good Habit", "phonetic": "Setting up a specific, quiet study spot for schoolwork", "image": "assets/habits-images/044_setting_up_a_specific_quiet_study_spot_for_schoolwork.png" },
    { "name": "Wiping down your shared computer keyboard or tablet screen", "capital": "Good Habit", "phonetic": "Wiping down your shared computer keyboard or tablet screen", "image": "assets/habits-images/045_wiping_down_your_shared_computer_keyboard_or_tablet_screen.png" },
    { "name": "Staring at a smartphone screen during a family dinner", "capital": "Bad Habit", "phonetic": "Staring at a smartphone screen during a family dinner", "image": "assets/habits-images/046_staring_at_a_smartphone_screen_during_a_family_dinner.png" },
    { "name": "Listening quietly without talking while a teacher explains a lesson", "capital": "Good Habit", "phonetic": "Listening quietly without talking while a teacher explains a lesson", "image": "assets/habits-images/047_listening_quietly_without_talking_while_a_teacher_explains_a.png" },
    { "name": "Keeping your fingernails neatly trimmed and clean", "capital": "Good Habit", "phonetic": "Keeping your fingernails neatly trimmed and clean", "image": "assets/habits-images/048_keeping_your_fingernails_neatly_trimmed_and_clean.png" },
    { "name": "Leaving a wet towel flat on your bedroom floor or carpet", "capital": "Bad Habit", "phonetic": "Leaving a wet towel flat on your bedroom floor or carpet", "image": "assets/habits-images/049_leaving_a_wet_towel_flat_on_your_bedroom_floor_or_carpet.png" },
    { "name": "Writing down important test dates on a master calendar", "capital": "Good Habit", "phonetic": "Writing down important test dates on a master calendar", "image": "assets/habits-images/050_writing_down_important_test_dates_on_a_master_calendar.png" },
    { "name": "Clearing your own plate and cup from the dining table", "capital": "Good Habit", "phonetic": "Clearing your own plate and cup from the dining table", "image": "assets/habits-images/051_clearing_your_own_plate_and_cup_from_the_dining_table.png" },
    { "name": "Carrying a heavy school backpack on just one shoulder strap", "capital": "Bad Habit", "phonetic": "Carrying a heavy school backpack on just one shoulder strap", "image": "assets/habits-images/052_carrying_a_heavy_school_backpack_on_just_one_shoulder_strap.png" },
    { "name": "Using your clothing sleeve to wipe a runny nose", "capital": "Bad Habit", "phonetic": "Using your clothing sleeve to wipe a runny nose", "image": "assets/habits-images/053_using_your_clothing_sleeve_to_wipe_a_runny_nose.png" },
    { "name": "Brushing your tongue while cleaning your teeth", "capital": "Good Habit", "phonetic": "Brushing your tongue while cleaning your teeth", "image": "assets/habits-images/054_brushing_your_tongue_while_cleaning_your_teeth.png" },
    { "name": "Putting on a clean pair of fresh socks every single day", "capital": "Good Habit", "phonetic": "Putting on a clean pair of fresh socks every single day", "image": "assets/habits-images/055_putting_on_a_clean_pair_of_fresh_socks_every_single_day.png" },
    { "name": "Drinking multiple sugary sodas instead of fresh water", "capital": "Bad Habit", "phonetic": "Drinking multiple sugary sodas instead of fresh water", "image": "assets/habits-images/056_drinking_multiple_sugary_sodas_instead_of_fresh_water.png" },
    { "name": "Checking your bike tires and brakes before going for a ride", "capital": "Good Habit", "phonetic": "Checking your bike tires and brakes before going for a ride", "image": "assets/habits-images/057_checking_your_bike_tires_and_brakes_before_going_for_a_ride.png" },
    { "name": "Picking your nose in public spaces around other people", "capital": "Bad Habit", "phonetic": "Picking your nose in public spaces around other people", "image": "assets/habits-images/058_picking_your_nose_in_public_spaces_around_other_people.png" },
    { "name": "Washing fruits and vegetables under clean water before eating", "capital": "Good Habit", "phonetic": "Washing fruits and vegetables under clean water before eating", "image": "assets/habits-images/059_washing_fruits_and_vegetables_under_clean_water_before_eatin.png" },
    { "name": "Licking your fingers clean instead of washing away sticky syrup", "capital": "Bad Habit", "phonetic": "Licking your fingers clean instead of washing away sticky syrup", "image": "assets/habits-images/060_licking_your_fingers_clean_instead_of_washing_away_sticky_sy.png" },
    { "name": "Thanking your school bus driver or lunch staff helpers", "capital": "Good Habit", "phonetic": "Thanking your school bus driver or lunch staff helpers", "image": "assets/habits-images/061_thanking_your_school_bus_driver_or_lunch_staff_helpers.png" },
    { "name": "Keeping an open cup of liquid right next to a laptop computer", "capital": "Bad Habit", "phonetic": "Keeping an open cup of liquid right next to a laptop computer", "image": "assets/habits-images/062_keeping_an_open_cup_of_liquid_right_next_to_a_laptop_compute.png" },
    { "name": "Putting items back exactly where they belong when finished", "capital": "Good Habit", "phonetic": "Putting items back exactly where they belong when finished", "image": "assets/habits-images/063_putting_items_back_exactly_where_they_belong_when_finished.png" },
    { "name": "Drinking out of someone else's personal water bottle", "capital": "Bad Habit", "phonetic": "Drinking out of someone else's personal water bottle", "image": "assets/habits-images/064_drinking_out_of_someone_elses_personal_water_bottle.png" },
    { "name": "Looking away at distant objects to rest eyes during screen time", "capital": "Good Habit", "phonetic": "Looking away at distant objects to rest eyes during screen time", "image": "assets/habits-images/065_looking_away_at_distant_objects_to_rest_eyes_during_screen_t.png" },
    { "name": "Telling minor lies to hide small behavioral mistakes", "capital": "Bad Habit", "phonetic": "Telling minor lies to hide small behavioral mistakes", "image": "assets/habits-images/066_telling_minor_lies_to_hide_small_behavioral_mistakes.png" },
    { "name": "Turning off the lights when leaving a room completely empty", "capital": "Good Habit", "phonetic": "Turning off the lights when leaving a room completely empty", "image": "assets/habits-images/067_turning_off_the_lights_when_leaving_a_room_completely_empty.png" },
    { "name": "Stretching your muscles regularly before playing intense sports", "capital": "Good Habit", "phonetic": "Stretching your muscles regularly before playing intense sports", "image": "assets/habits-images/068_stretching_your_muscles_regularly_before_playing_intense_spo.png" },
    { "name": "Listening to music at maximum blast through your headphones", "capital": "Bad Habit", "phonetic": "Listening to music at maximum blast through your headphones", "image": "assets/habits-images/069_listening_to_music_at_maximum_blast_through_your_headphones.png" },
    { "name": "Tracking daily homework assignments inside a planner notebook", "capital": "Good Habit", "phonetic": "Tracking daily homework assignments inside a planner notebook", "image": "assets/habits-images/070_tracking_daily_homework_assignments_inside_a_planner_noteboo.png" },
    { "name": "Washing your hands immediately after playing with your pets", "capital": "Good Habit", "phonetic": "Washing your hands immediately after playing with your pets", "image": "assets/habits-images/071_washing_your_hands_immediately_after_playing_with_your_pets.png" },
    { "name": "Shouting directly over someone else during a classroom conversation", "capital": "Bad Habit", "phonetic": "Shouting directly over someone else during a classroom conversation", "image": "assets/habits-images/072_shouting_directly_over_someone_else_during_a_classroom_conve.png" },
    { "name": "Cleaning your bedroom once a week without being asked to do so", "capital": "Good Habit", "phonetic": "Cleaning your bedroom once a week without being asked to do so", "image": "assets/habits-images/073_cleaning_your_bedroom_once_a_week_without_being_asked_to_do_.png" },
    { "name": "Washing your hands right after coughing into a disposable tissue", "capital": "Good Habit", "phonetic": "Washing your hands right after coughing into a disposable tissue", "image": "assets/habits-images/074_washing_your_hands_right_after_coughing_into_a_disposable_ti.png" },
    { "name": "Using your teeth to pry open tough plastic packaging or bottle caps", "capital": "Bad Habit", "phonetic": "Using your teeth to pry open tough plastic packaging or bottle caps", "image": "assets/habits-images/075_using_your_teeth_to_pry_open_tough_plastic_packaging_or_bott.png" },
    { "name": "Inviting a student who is sitting all alone to play with you", "capital": "Good Habit", "phonetic": "Inviting a student who is sitting all alone to play with you", "image": "assets/habits-images/076_inviting_a_student_who_is_sitting_all_alone_to_play_with_you.png" },
    { "name": "Walking across clean home carpets while wearing dirty outdoor shoes", "capital": "Bad Habit", "phonetic": "Walking across clean home carpets while wearing dirty outdoor shoes", "image": "assets/habits-images/077_walking_across_clean_home_carpets_while_wearing_dirty_outdoo.png" },
    { "name": "Following a predictable, organized morning routine for school", "capital": "Good Habit", "phonetic": "Following a predictable, organized morning routine for school", "image": "assets/habits-images/078_following_a_predictable_organized_morning_routine_for_school.png" },
    { "name": "Throwing trash straight out of a moving vehicle window", "capital": "Bad Habit", "phonetic": "Throwing trash straight out of a moving vehicle window", "image": "assets/habits-images/079_throwing_trash_straight_out_of_a_moving_vehicle_window.png" },
    { "name": "Asking an adult for help calmly when an electronic device freezes", "capital": "Good Habit", "phonetic": "Asking an adult for help calmly when an electronic device freezes", "image": "assets/habits-images/080_asking_an_adult_for_help_calmly_when_an_electronic_device_fr.png" },
    { "name": "Washing your hands right after sneezing directly into them", "capital": "Good Habit", "phonetic": "Washing your hands right after sneezing directly into them", "image": "assets/habits-images/081_washing_your_hands_right_after_sneezing_directly_into_them.png" },
    { "name": "Reading a book in bed to wind down instead of watching videos", "capital": "Good Habit", "phonetic": "Reading a book in bed to wind down instead of watching videos", "image": "assets/habits-images/082_reading_a_book_in_bed_to_wind_down_instead_of_watching_video.png" },
    { "name": "Leaving a big mess on the counter after baking or cooking food", "capital": "Bad Habit", "phonetic": "Leaving a big mess on the counter after baking or cooking food", "image": "assets/habits-images/083_leaving_a_big_mess_on_the_counter_after_baking_or_cooking_fo.png" },
    { "name": "Maintaining straight, healthy body posture while sitting at a desk", "capital": "Good Habit", "phonetic": "Maintaining straight, healthy body posture while sitting at a desk", "image": "assets/habits-images/084_maintaining_straight_healthy_body_posture_while_sitting_at_a.png" },
    { "name": "Flushing the toilet and checking that it is clean after every use", "capital": "Good Habit", "phonetic": "Flushing the toilet and checking that it is clean after every use", "image": "assets/habits-images/085_flushing_the_toilet_and_checking_that_it_is_clean_after_ever.png" },
    { "name": "Peeling or picking off dry skin patches from your lips", "capital": "Bad Habit", "phonetic": "Peeling or picking off dry skin patches from your lips", "image": "assets/habits-images/086_peeling_or_picking_off_dry_skin_patches_from_your_lips.png" },
    { "name": "Asking for permission before using items that belong to siblings", "capital": "Good Habit", "phonetic": "Asking for permission before using items that belong to siblings", "image": "assets/habits-images/087_asking_for_permission_before_using_items_that_belong_to_sibl.png" },
    { "name": "Choosing physically active playground games over video games", "capital": "Good Habit", "phonetic": "Choosing physically active playground games over video games", "image": "assets/habits-images/088_choosing_physically_active_playground_games_over_video_games.png" },
    { "name": "Washing your bed sheets and pillowcases on a regular schedule", "capital": "Good Habit", "phonetic": "Washing your bed sheets and pillowcases on a regular schedule", "image": "assets/habits-images/089_washing_your_bed_sheets_and_pillowcases_on_a_regular_schedul.png" },
    { "name": "Eating sweet midnight snacks right after you brushed your teeth", "capital": "Bad Habit", "phonetic": "Eating sweet midnight snacks right after you brushed your teeth", "image": "assets/habits-images/090_eating_sweet_midnight_snacks_right_after_you_brushed_your_te.png" },
    { "name": "Wiping down shared playground sports gear after using it", "capital": "Good Habit", "phonetic": "Wiping down shared playground sports gear after using it", "image": "assets/habits-images/091_wiping_down_shared_playground_sports_gear_after_using_it.png" },
    { "name": "Setting aside time to read books for fun every day", "capital": "Good Habit", "phonetic": "Setting aside time to read books for fun every day", "image": "assets/habits-images/092_setting_aside_time_to_read_books_for_fun_every_day.png" },
    { "name": "Leaving a scattered trail of dirty laundry on your bedroom floor", "capital": "Bad Habit", "phonetic": "Leaving a scattered trail of dirty laundry on your bedroom floor", "image": "assets/habits-images/093_leaving_a_scattered_trail_of_dirty_laundry_on_your_bedroom_f.png" },
    { "name": "Buckling your seatbelt as soon as you sit inside a car", "capital": "Good Habit", "phonetic": "Buckling your seatbelt as soon as you sit inside a car", "image": "assets/habits-images/094_buckling_your_seatbelt_as_soon_as_you_sit_inside_a_car.png" },
    { "name": "Covering a heavy cough using your bare open hands", "capital": "Bad Habit", "phonetic": "Covering a heavy cough using your bare open hands", "image": "assets/habits-images/095_covering_a_heavy_cough_using_your_bare_open_hands.png" },
    { "name": "Practicing daily gratitude by counting good things in your life", "capital": "Good Habit", "phonetic": "Practicing daily gratitude by counting good things in your life", "image": "assets/habits-images/096_practicing_daily_gratitude_by_counting_good_things_in_your_l.png" },
    { "name": "Leaving hot hair styling tools or gaming rigs plugged in all day", "capital": "Bad Habit", "phonetic": "Leaving hot hair styling tools or gaming rigs plugged in all day", "image": "assets/habits-images/097_leaving_hot_hair_styling_tools_or_gaming_rigs_plugged_in_all.png" },
    { "name": "Drying your hands completely on a clean towel after washing them", "capital": "Good Habit", "phonetic": "Drying hands completely on a clean towel after washing them", "image": "assets/habits-images/098_drying_your_hands_completely_on_a_clean_towel_after_washing_.png" },
    { "name": "Tidying your desk space immediately after finishing a project", "capital": "Good Habit", "phonetic": "Tidying desk space immediately after finishing a project", "image": "assets/habits-images/099_tidying_your_desk_space_immediately_after_finishing_a_projec.png" },
    { "name": "Actively choosing good daily habits over easy, bad choices", "capital": "Good Habit", "phonetic": "Actively choosing good daily habits over easy, bad choices", "image": "assets/habits-images/100_actively_choosing_good_daily_habits_over_easy_bad_choices.png" }
  ]
      }
